### PR TITLE
drop i386 and clean up

### PR DESCRIPTION
**Pull request by stefansaraev**
its about time.

### CODE REVIEW

**Comment by sraue** [comment]
wait with this until the first kodi-15 beta releases are released

**Comment by stefansaraev** [comment]
installer changes dropped. sure should wait

**Comment by mrdominuzq** [comment]
shouldnt nasm also be removed :)?

**Comment by vpeter4** [comment]
Nasm is used for toolchain.

**Comment by mrdominuzq** [comment]
nasm got added Again because kodi requiered it on 32bit :) correct ?

**Comment by vpeter4** [comment]
Seems correct - nasm not needed for x86_64 build and RPi.

**Pull request merged**
