### PR TITLE
Updated ouya controller patch

### PR DESCRIPTION
**Pull request by lrusak**

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks. on frm me. @sraue do you want this in ?

**Comment by sraue** [comment]
yes i want

**Comment by lrusak** [comment]
@sraue I didn't do arm configs because you won't be able to use the controller in Kodi on those platforms anyway.

**Comment by sraue** [comment]
@lrusak then it should be disabled, not tested the patch yet but i thing after merge the build asks... would be nice if kodi would support controllers on arm plattforms, maybe another thing where libinput is usefull?

**Comment by lrusak** [comment]
Added to RPi's configs as they already have the other controllers set as well.

**Pull request merged**
