### PR TITLE
pvr.mythtv: update to pvr.mythtv-5450056

### PR DESCRIPTION
**Pull request by CvH**
v2.8.4 @janbar 
this is the correct, up to date + stable, version for isengard right ?

### CODE REVIEW

**Comment by chewitt** [comment]
@CvH - if bumping we also need to consider how/where we get the source package from. Please take a look at the mkpkg scripts for kodi and kodi-binary addons.

**Comment by janbar** [comment]
Correct. The last version i released for Isengard in repository "kodi-pvr" is 2.8.4 with this commit.

**Comment by janbar** [comment]
The official source of the package for the addon is "https://github.com/kodi-pvr/pvr.mythtv" and you have to choose de right branch named like kodi core, i.e Isengard , and next will be Jarvis.
Thanks

**Comment by janbar** [comment]
Also, I think users will be happy when OpenELEC repo will up to date.

**Comment by chewitt** [comment]
closing as superceded by #4531

**Pull request closed without merging**
