### PR TITLE
WeTek kernel and Mali GPU driver updates

### PR DESCRIPTION
**Pull request by codesnake**
* Update Amlogic kernel to 3.10-716f179 (includes new Mali GPU driver r5p1-01rel0)
* Update proprietary Mali OpenGL ES libraries for Meson6 to match the new driver

This PR fixes an issue with GUI tearing on WeTek Play and OE box.

### CODE REVIEW

**Comment by chewitt** [comment]
is this also needed for 6.0.x?

**Comment by codesnake** [comment]
@chewitt Would be really good to have it also in 6.0.x.

**Comment by stefansaraev** [comment]
thanks.

do we also need updated opengl-meson8 btw ?

**Comment by codesnake** [comment]
@stefansaraev I will update my wetek_core branch tonight with all required changes as well.

**Comment by stefansaraev** [comment]
np. I realized you also uploaded meson8 tar, already adjusted here, seems to be runing ok.

**Comment by wrxtasy** [comment]
meson8 Works fine on a S805 ODROID C1+ as well.
Smooth as. All AML OE platforms will benefit from these new f5p1 drivers :+1: 

Best fix I've seen for AML users in a long time !

**Pull request merged**
