### PR TITLE
[linux] update to 4.1

### PR DESCRIPTION
**Pull request by lrusak**
This is a placeholder until final is released.

A few patches need reworking to be compatible with 4.1 ;)

### CODE REVIEW

**Comment by stefansaraev** [comment]
does this fix any known 4.0 issues ?

**Comment by lrusak** [comment]
From what I've read
* Better performance for Cherry Trail / Bay Trail Intel hardware. 
* ARM and x86 power management improvements. 

Other than that I'm not on the up and up with kernel bugs ;)
Are there any bugs currently that effect OpenELEC?

**Comment by stefansaraev** [comment]
at some point, the bumping game we play for years, should end. for next stable, we must pick a serie (be it 4.0 or 4.1 or whatever) and not bump it. up to @sraue

**Comment by lrusak** [comment]
Well I do not think this should go into 6.0. We should leave it at kernel 4.0 for OE 6.0.

**Comment by fritsch** [comment]
This is this time not so easy to decide. If you follow intel's IRC ... in
any case, not matter what we ship. We need to make sure to test on the
"default" systems:

Intel Nucs (SNB, IVB, HSW, BDW, chromebox, Celeron Atom), especially the
freezing issue on Celeron Atom J1900 should still be workarounded ... see
current patches
Nvidia GT610+
AMD (E350, 5150 series) and so on.

GPU world on linux is a steadily changing environment ...

2015-05-27 19:44 GMT+02:00 Lukas Rusak <notifications@github.com>:

> Well I do not think this should go into 6.0. We should leave it at kernel
> 4.0 for OE 6.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/4165#issuecomment-106009010>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by stefansaraev** [comment]
if you ask me, we are too late.

**Comment by CvH** [comment]
fyi, 4.1 become [LTS Kernel](https://plus.google.com/+gregkroahhartman/posts/ShnsSWMAKKC)

**Comment by stefansaraev** [comment]
> fyi, 4.1 become [LTS Kernel](https://plus.google.com/+gregkroahhartman/posts/ShnsSWMAKKC)

yup. in this case, 4.1 is better candidate for next stable, than 4.0. so we shoould bump (now or when it's released) and stick with it for the whole 6.x release cycle. @sraue @lrusak

**Comment by fritsch** [comment]
+1 here

my new BSW needs it :-)

2015-06-10 16:50 GMT+02:00 Stefan Saraev <notifications@github.com>:

> fyi, 4.1 become LTS Kernel
> <https://plus.google.com/+gregkroahhartman/posts/ShnsSWMAKKC>
>
> yup. in this case, 4.1 is better candidate for next stable, than 4.0. so
> we shoould bump (now or when it's released) and stick with it for the whole
> 6.x release cycle. @sraue <https://github.com/sraue> @lrusak
> <https://github.com/lrusak>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/4165#issuecomment-110782500>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by stefansaraev** [comment]
#4193

**Pull request closed without merging**
