### PR TITLE
Fix compile flags

### PR DESCRIPTION
**Pull request by vpeter4**
Issues detected with new project I'm working on which is using some different compiler flags.
Tested on all current projects.

### CODE REVIEW

**Comment by stefansaraev** [comment]
ok for others.

**Comment by stefansaraev** [comment]
however, the plymouth change doesnt hurt.

@sraue any objections ?

**Comment by stefansaraev** [comment]
humh. the plymouth commit completely breaks splash loading for me, on wetek play. I'll revert.

**Comment by MilhouseVH** [comment]
Also on Pi, currently in the middle of confirming this but you may have beaten me to it. :)

**Comment by stefansaraev** [comment]
revert fixes it for me. would be nice if you can confirm @MilhouseVH - revert, clean linux busybox and plymouth-lite (just in case, to be 100% sure) then rebuild. thanks ;)

**Comment by MilhouseVH** [comment]
Did you revert the whole PR or just the plymouth-lite commit? I tried reverting only the latter but still had a broken splash, then reverted the whole PR and splash is working. I'll run some more builds and confirm shortly.

**Comment by stefansaraev** [comment]
> Did you revert the whole PR or just the plymouth-lite commit?

only plymouth-lite. scripts/clean linux; scripts/clean plymouth-lite is a must.

**Comment by MilhouseVH** [comment]
Yep, did that but maybe something else went tits up - will confirm in a bit.

**Comment by MilhouseVH** [comment]
Yep confirmed - revert bdde001075b23808cee9e12c7e8f7c31500108ec and splash works again. Many thanks.

**Comment by stefansaraev** [comment]
thanks. lets revert for now then

**Comment by vpeter4** [comment]
I checked on Generic build. But could be possible that something went wrong with my test and didn't actually tested this change.
But ply-image is not real static binary - it still needs libc.so. With my change it needs libm.so too. That's why it fails.
Revert and I will reinvestigate.

**Comment by stefansaraev** [comment]
> But ply-image is not real static binary - it still needs libc.so

yes. it was never intendded to be a "real" static binary. but we dont want libm.so in initrd

extending -22-link-static.patch with "-Wl,-Bstatic -lm -Wl,-Bdynamic" will probably help on your use case, that's why I initialy pointed out that patch ;)

**Comment by vpeter4** [comment]
So it is semi-static then :-)
Anyway, will check again.

**Pull request merged**
