### PR TITLE
prepare for kodi-15

### PR DESCRIPTION
**Pull request by stefansaraev**
this is for people who want to self-build with kodi-master. not meant for merging

@sraue @MartijnKaijser @MilhouseVH @da-anda

sources hosted on my server, I'll keep this branch updated.

EDIT: tested generic64 and wetek.play. RPi builds will fail (project specific patches) selfbuilders know what to do ;)

### CODE REVIEW

**Comment by InuSasha** [comment]
I get 404 for
http://saraev.ca/openelec/pvr.pctv-dbdeb3a.tar.xz
http://saraev.ca/openelec/pvr.filmon-d4b0045.tar.xz

**Comment by MilhouseVH** [comment]
mkpkg_kodi is failing:
```
neil@nm-linux:~/projects/packages$ /home/neil/projects/OpenELEC.tv/tools/mkpkg/mkpkg_kodi
[mkpkg] Checking out git://github.com/xbmc/xbmc.git ...
Cloning into 'kodi-master.git'...
remote: Counting objects: 320772, done.
remote: Total 320772 (delta 0), reused 0 (delta 0), pack-reused 320772
Receiving objects: 100% (320772/320772), 495.54 MiB | 1.96 MiB/s, done.
Resolving deltas: 100% (230260/230260), done.
Checking connectivity... done.
[mkpkg] Checking out https://github.com/xbmc/kodi-platform ...
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
/home/neil/projects/OpenELEC.tv/tools/mkpkg/mkpkg_kodi: 40: cd: can't cd to kodi-platform.git
/home/neil/projects/packages
/home/neil/projects/packages
warning: refname '68315f0' is ambiguous.
fatal: A branch named '68315f0' already exists.
Deleted branch 68315f0 (was 68315f0).
Already on 'master'
Your branch is up-to-date with 'origin/master'.
cat: kodi-master.git/project/cmake/addons/addons/*.*/*.*.txt: No such file or directory
cat: kodi-master.git/project/cmake/addons/addons/*.*/*.*.txt: No such file or directory
[mkpkg] Checking out master ...
fatal: repository 'master' does not exist
/home/neil/projects/OpenELEC.tv/tools/mkpkg/mkpkg_kodi: 92: cd: can't cd to kodi-master.git
grep: version.txt: No such file or directory
grep: version.txt: No such file or directory
grep: version.txt: No such file or directory
.--68315f0
[mkpkg] Seperating skin.confluence ...
/home/neil/projects/packages
mv: cannot stat ‘kodi-.--68315f0/addons/skin.confluence’: No such file or directory
```

**Comment by stefansaraev** [comment]
our buildsystem requires bash. including mkpkg scripts.

**Comment by MilhouseVH** [comment]
Thanks, it's a lot happier with the addition of #!/bin/bash.

**Comment by nmaclean** [comment]
timeout on 
http://saraev.ca/openelec/audioencoder.lame-3eb59de.tar.xz

**Comment by MilhouseVH** [comment]
```
--2015-03-07 12:49:20--  http://saraev.ca/openelec/audioencoder.flac-84acb14.tar.xz
Resolving saraev.ca (saraev.ca)... failed: Name or service not known.
wget: unable to resolve host address 'saraev.ca'
--2015-03-07 12:49:28--  http://sources.openelec.tv/mirror/audioencoder.flac/audioencoder.flac-84acb14.tar.xz
Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33
Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-03-07 12:49:28 ERROR 404: Not Found.
```

**Comment by stefansaraev** [comment]
hey, package it yourself!

my servers down because of 110kV power cut in the area they are located. 150k people with no electricity, nobody gives a f**k about few sources missing atm.

**Comment by MilhouseVH** [comment]
F**ck me, grumpy or what? How are we supposed to know?

Are you really interested in problems with this PR, or do you intend on snapping at everyone with snarky comments? Maybe I've got better things to do on a Saturday afternoon...

**Comment by stefansaraev** [comment]
no.I am not interested.

**Comment by MilhouseVH** [comment]
@stefansaraev: You really shouldn't throw stones in glass houses.

**Pull request closed without merging**
