### PR TITLE
Revert "update to 0.2.5598, update link, fix licence"

### PR DESCRIPTION
**Pull request by stefansaraev**
This reverts commit e3e071547d327a961ae6cbe2b9b6ff9c93e9a2bb.

openmpt is now broken. I require a revert. ref #4319

### CODE REVIEW

**Comment by stefansaraev** [comment]
fyi @qods

**Comment by qods** [comment]
They changed the download server file in the last 1-2 days. I will update it once again in few minutes.
Here is the recent link that should work for a long time and that i would add in few minutes to a recent change.
http://lib.openmpt.org/files/libopenmpt/src/libopenmpt-0.2.5602-beta14.tar.gz

**Comment by qods** [comment]
Here is the updated pull request:
https://github.com/OpenELEC/OpenELEC.tv/pull/4357

**Comment by stefansaraev** [comment]
no you did not get it right. I do not want you to touch the package. I want it reverted.

**Comment by vpeter4** [comment]
qods, don't update packages without good reason. We already have enough problems and this doesn't help.

**Comment by stefansaraev** [comment]
and it's not about some broken link btw. it fails at build time (you obviously did not built test, and you did not build test your new PR, too). and you obviously fialed to runtime test audiodecoder.openmpt. because you never built it, for any OE supported platform.

fyi. I am (was) the one, who maintain(ed) the repos for years. for past xx months, since I said "fuck off" because of shit like this. not a single fix was pushed to repos by others (where have you been? why did you not take over?). 

so right now, I diceded to do some good, and you broke my build env. with untested PRs. thanks much! 

and from what I see, you are about to break it one more time (your SHOCKING! CRITICAL SECURITY ISSUE pr).

so, tell me, @qods, why the hell I still waste time on this ?

**Comment by stefansaraev** [comment]
nevermind. glibc was bumped in master. I wont rebuild anything against it and push to repos. anyway. this was not worth the trouble.

**Pull request closed without merging**
