### PR TITLE
Add screensavers

### PR DESCRIPTION
**Pull request by notspiff**
This adds some screensaver addons.

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks

where's the source for soil? 

http://www.lonesock.net/files/soil.zip re-packaged ?

**Comment by notspiff** [comment]
yes, that's what i did.

**Comment by stefansaraev** [comment]
cool. I'll do build test

feel free to pick https://github.com/stefansaraev/OpenELEC.tv/commit/e4448b7e9e4f1e5a914690115276f3c649ffb2b0

split and squash into your commits if you want

**Comment by notspiff** [comment]
picked/squashed. sorry, i forgot about those..

**Comment by stefansaraev** [comment]
here, soil picked up host g++

```
CXX="$CXX" CXXFLAGS="-fPIC -O2"
```

^ fixed it in make_target()

**Comment by notspiff** [comment]
yeh, but it's pure C code hence i didn't care.. but i'll add for sanity.

**Pull request merged**
