### PR TITLE
projects/WeTek_Play: Activate Ethernet and WiFi LEDs

### PR DESCRIPTION
**Pull request by codesnake**
Add a patch that activates the Ethernet and WiFi LEDs on the front panel.

### CODE REVIEW

**Comment by stefansaraev** [comment]
cool ;)

**Comment by Memphiz** [comment]
@codesnake those are not exposed as generic leds via sysfs - are they?

**Comment by codesnake** [comment]
@Memphiz Most likely no

**Comment by Memphiz** [comment]
not at home atm - which colors do those leds have and are they turned on solid or flickering? I can look into making them available via sysfs and mimic current behavior by using triggers (there wil be other users who want to be able to turn the leds off like me for not beeing distracted)

**Comment by codesnake** [comment]
@Memphiz They are blue and solid

**Pull request merged**
