### PR TITLE
New upstream version requires change of makefile patch

### PR DESCRIPTION
**Pull request by gdachs**
New upstream version has now Documentation for the wirbelscan extension and feature complete.
At least for now ;)

### CODE REVIEW

**Comment by stefansaraev** [comment]
ouch. what happened here ? 
better use topic branches and dont send PRs from master :)

**Comment by gdachs** [comment]
What do you mean? What did I do wrong? The first PR was sent from master too.

**Comment by stefansaraev** [comment]
look at commits... I see the other PR + merge commits..

**Comment by gdachs** [comment]
Okay, but the only changed files are that, that I want to get merged. What shall I do now?

**Comment by fritsch** [comment]
Rebase -i on oe master then force push

2015-01-16 10:22 GMT+01:00 gdachs <notifications@github.com>:

> Okay, but the only changed files are that, that I want to get merged. What
> shall I do now?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/3799#issuecomment-70227608>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by gdachs** [comment]
Sorry, I never did this rebase before. It scares me, I am afraid to loose my changes. Can you hold my hand on this?

**Comment by fritsch** [comment]
1) git branch xyz # this will backup everything you do into the branch
named xyz
2) git fetch oe-upstream #this is the remote you track openelec
3) git rebase -i oe-upstream/master #here only "pick" your changes
4.) git push -f yourremote yourbranch

2015-01-16 10:30 GMT+01:00 gdachs <notifications@github.com>:

> Sorry, I never did this rebase before. It scares me, I am afraid to loose
> my changes. Can you hold my hand on this?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/3799#issuecomment-70228572>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by gdachs** [comment]
Picked the first, squashed the rest, but get:
error: could not apply 94f8f84... new package vdr-plugin-resfulapi
:(

**Comment by fritsch** [comment]
Yeah, fix your merge conflicts. You seem to have merged other stuff into your tree.

**Comment by gdachs** [comment]
I think I got it now. I had to pick and squash only the last 2 commits, because the other have been applied by stefansaraev already.

Better now?

**Comment by fritsch** [comment]
A lot of whitespace changes and the fix mostly removes a method and changing some upstream version :-) Are you sure that's everything you need?

**Comment by gdachs** [comment]
yes, much more I have done in this upstream version.

**Comment by stefansaraev** [comment]
thanks. I'll not do vdr-addon bump this time. shall wait at least one week and see if we have something else to add.

**Pull request merged**
