### PR TITLE
[RBP] Add new kernel config options

### PR DESCRIPTION
**Pull request by MilhouseVH**
Adds support for SDIO and RPi official touchscreen, as well as other touchscreen hardware.

### CODE REVIEW

**Comment by stefansaraev** [comment]
-1 on touchscreen :)

**Comment by fritsch** [comment]
Yeah - we never wanted to support touchscreens in OE ... but now - we got a maintainer :-)

**Comment by popcornmix** [comment]
Thanks @MilhouseVH.
+1 from me

**Comment by fritsch** [comment]
Yeah - as said yesterday. The biggest user group OE has by far far far is the Raspberry Pi - and if this is a new gadget only 10% of those users will use than this is still more than ATV, IMX and wetek and a large part of x86_64 together.

So - it's a nobrainer - OE as a PI distribution - needs support for it.

**Pull request merged**
