### PR TITLE
revert ce937bb..a61ad19

### PR DESCRIPTION
**Pull request by stefansaraev**
this reverts last 44 commits, which contain changes pushed by me to
master, some are plain wrong on OE 5.0 (not tested at all or they depend
on other commits not cherry-picked)

I disagree with my experimental stuff ending up in stables, I give no
guarantee of anything working on 5.0. in fact it's now very
broken (hint coredumps filling your sdcard/hdd), so I require an immediate revert

### CODE REVIEW

**Comment by stefansaraev** [comment]
and please dont revert just my changes. push this PR, tag 5.0.1 and lets have at least one quite well working stable. I've spent lot of hours fixing 5.0 bugs because it was supposed to be stable, and now this.. thanks.

**Comment by fritsch** [comment]
I am the same oppinion here. The IMX changes are not yet ready for prime time - i am testing those since 3 days to get some feedback for the devs that write it.

Don't risk those regressions for stable.

We can make a "faster" 5.0.2 if those are tested and the missing features are integrated (RenderCapture).

**Comment by stefansaraev** [comment]
I will merge this in 24 hours if no objections and @sraue is not faster than me. if you have any, please feel free to discuss here.

meanwhile, please avoid pushing to 5.0, I'll take care to revert everything new and will add it to this PR.

**Comment by vpeter4** [comment]
So what went wrong here? To fast fingers?

**Comment by stefansaraev** [comment]
re whats wrong besides my cherry-picked commits:

- @fritsch imx changes. they have no place here.
- automake bumped. I stil (well, again) build addons and maintain addon repos. I build from 5.0 branch for a good reason. I dont trust, and disagree with changes to toolchain/hosttools for NO GOOD reason
- elfutils bumped for no reason. build fails. one got a workaround to make it compile.
- curl bumped for no (visible) reason. it does not fix or reference a ticket here on gh.
- libjpeg-turbo bumped for no (visible) reason. it does not fix or reference a ticket here on gh.
- minor bumps on llvm/xz/libdrm, probably safe, but I dont see what bugs are fixed.

llvm/libdrm/curl/libjpeg bumped without propper testing. only @sraue tests. regressionsanyone? thats well.. not acceptable in a "stable" branch, unless those are known to fix KNOWN bugs. I see none.

got it?

if you dont have arguments against merging this pr, better avoid spaming others, thanks in advance.

**Comment by sraue** [comment]
and why to revert all the other stuff too? if you have reasons to have stuff not in 5.0 then revert only the affected commits.

**Comment by fritsch** [comment]
On moment here. It's not about "having reason to revert", it's about "reason to commit" - and the mentioned commits simply have absolutely _no_reason_ - it is the old song: "Latest and greatest and biggest and fattest - don't care about regressions" and this is not good!

**Comment by stefansaraev** [comment]
well thank you very much!

> if you have reasons to have stuff not in 5.0 then revert only the affected commits.

not going to happen. I just stopped caring for the so-called "stables", that were never stables, and seems they will never be.

do whatever you want, it. it's your distro. your bugtracker and forums. 's your problem now

**Comment by stefansaraev** [comment]
#3866

**Pull request closed without merging**
