### PR TITLE
Python: remove distutilcross not needed

### PR DESCRIPTION
**Pull request by mrdominuzq**
i havent tested the other python packages, because they are not included and maybe should be remove.

and i couldn't find anything about pycrypto, so maybe somebody could tell me what depends on it :)

### CODE REVIEW

**Comment by stefansaraev** [comment]
I dont think this is good idea.

**Comment by mrdominuzq** [comment]
it shouldnt cause any harm :)

**Comment by stefansaraev** [comment]
are you sure, even compiling for arm, on x86_64 host ? how does setuptools:host handle that ?

**Comment by mrdominuzq** [comment]
the only 2 who failed was pillow and pycrypto, that's why i added the cppflags. but i dont have the chance to test it since my rpi is not a home right now :)

but here's the test build
https://drive.google.com/file/d/0B-2ANc5gpRgBQWp6ZGZDbEJpdGM/view?usp=sharing

**Comment by stefansaraev** [comment]
it's not only cppflags. it's a new world of mess. I'd keep distutilcross as is.

**Comment by mrdominuzq** [comment]
after having a look at it again, found some missing file with setuptools.

it's missing libtiff and freetype. https://www.diffchecker.com/ejve2ddw
so your right, stay with distutilcross :)

sorry for the waste of time ;)

**Comment by stefansaraev** [comment]
np. it's not a waste of time.

**Comment by mrdominuzq** [comment]
it's a good reminder to absolutely certain  when making changes :)

**Pull request closed without merging**
