### PR TITLE
plymouth-lite: black background in distro based splash

### PR DESCRIPTION
**Pull request by vpeter4**

### CODE REVIEW

**Comment by lrusak** [comment]
:+1: looks great

**Comment by vpeter4** [comment]
Yes, thanks to Klojum. I would use erase tool in image editor if he didn't provide this two images :)

**Comment by stefansaraev** [comment]
huh. depeted wrong branch ?

**Comment by vpeter4** [comment]
All I can say is "o *****". Will send new PR.

**Pull request closed without merging**
