### PR TITLE
New Package - mt7601u

### PR DESCRIPTION
**Pull request by lrusak**
This add support for the mt7601u chipset used in some wireless devices.

This is a rebase of #3494

### CODE REVIEW

**Comment by lrusak** [comment]
The reason imx6 and wetek builds were left out is because this driver will only work with kernel 3.19 or newer.

So either we have to use the older outdated version of the driver or we just don't include it for wetek/imx6

**Comment by fritsch** [comment]
Thought that - okay, leave it out - we don't want to fiddle arround with non upstream drivers too much. Btw. kernel 4.0 is coming - all fine with that already?

**Comment by chewitt** [comment]
@lrusak: I made the previous MT7601 package out of boredom one evening on a very dull business trip to Kuwait. I have no hardware to test anything with so I recommend we commit to master and offer-up some RPi/Generic builds for people test.

**Comment by lrusak** [comment]
@fritsch yes, I build it against current master which includes kernel 4.0

@chewitt agreed.

**Comment by miltador** [comment]
I think this driver can be bumped to latest rev. available on kuba-moo repo.

**Comment by sraue** [comment]
@lrusak please update the driver to the last rev, then i will include

**Comment by lrusak** [comment]
Updated, package is here, https://dl.dropboxusercontent.com/u/21742150/mt7601u-ba391b3.tar.xz

Also note that this needs OpenELEC/wlan-firmware#9

**Comment by chrisTRD** [comment]
Hi everybody,

I´m entirely new to the Linux community and I´m sorry to sound like a retard, but could someone briefly explain to me what I have to do to get my WiFi adapter with this chip running on my Raspberry Pi 2? It´s currently using OpenELEC 5.0.8, should be the latest version.

Any help is highly appreciated,
chris

**Comment by chewitt** [comment]
You can self-build with the commits in this PR if you have either the skills to do it or the initiative to read the long-standing instructions in the wiki and have a go. If not, be patient, wait for this PR to appear in a future release, and defer further chit-chat on the subject to the forums.

**Comment by miltador** [comment]
Update package please to latest rev, important bug fixed - https://github.com/kuba-moo/mt7601u/issues/14

**Pull request merged**
