### PR TITLE
Pick some commits for openelec-6.0

### PR DESCRIPTION
**Pull request by lrusak**
A final few fixes and tweaks that should make it into openelec 6.0

Update to kodi 15.2 final

@sraue please review

### CODE REVIEW

**Comment by fritsch** [comment]
Push those, too ... we have not a single need to wait for 6.0 anymore with kodi 15.2 is out ... let's not fuck it up in the last minute by bumping some random patches and then press the release button ...

**Comment by sraue** [comment]
please dont push such PRs we still sync master with openelec-6.0 branch, for new stuff we have openelec-next branch

**Comment by fritsch** [comment]
Those are cherry-picks - every "sync" will get them easily ...

**Comment by odc2** [comment]
Could you please help fixing the VDR problem? VDR is the only official way to watch live-TV and i tested on two different machines with different hardware and different DVB (one DVB-S and other DVB-T) and both was not propperly working.

This is the Bug i am talking about: https://github.com/OpenELEC/OpenELEC.tv/issues/4351

**Pull request merged**
