### PR TITLE
linux-imx6: update to latest stable/linux-3.14.y - Linux 3.14.36

### PR DESCRIPTION
**Pull request by piso77**
Rebase the linux-imx6 kernel to the latest stable/linux-3.14.y kernel available - 3.14.36.

Tested on my cubox-i-pro.

Signed-off-by: Paolo Pisati <p.pisati@gmail.com>

### CODE REVIEW

**Comment by stefansaraev** [comment]
no kernel bumps in 5.0

offtopic: imx6 kernel is a damn huge mess ;(

**Comment by piso77** [comment]
???

i see all kinds of kernel bumps for the raspy2

**Comment by stefansaraev** [comment]
this should go first in master. nothing goes directly to 5.0, unless it's 5.0 specific AND fixes known bugs

**Comment by fritsch** [comment]
@stefansaraev it might look scary but in fact it's "just a dot release", e.g. a linux stable update - though we have no idea if it breaks anything in our really large patchset :-)

**Comment by mrdominuzq** [comment]
Are 3.19 not mature enough for Imx6 :)?

**Comment by stefansaraev** [comment]
@fritsch I have seen enough regressions in .dot kernel releases. still it should go FIRST in master.
@mrdominuzq nop

**Comment by piso77** [comment]
ok, can you pull it in master or do you need another pull request?

**Comment by fritsch** [comment]
@stefansaraev yes, I have also - far too often.

@mrdominuzq sadly no - the 3.14 kernel we ship is a patched together, partly non upstream collection of "maybe working" patches. So @stefansaraev is fully right - we touch a very, very fragile eco system here.

**Comment by stefansaraev** [comment]
sent it to master and close this. @sraue decides if he wants to cherry pick for OE5. 
I, personaly dont mind cherry picking for stable. imx6 is fucked up enough already. but as said, nothing goes directly into 5.0 branch. it makes no sense to push to 5.0 but not master.

**Comment by mrdominuzq** [comment]
maybe one day in a beautiful World it Will follow The Main kernel :D

**Comment by fritsch** [comment]
https://www.youtube.com/watch?v=5j_-T4cfSYE <- The day that never comes ...

**Comment by piso77** [comment]
It's the same old story - the silicon vendor creates a BSP for a SOC on a kernel version, then completely forget to push the bits upstream and all the downstream user of that silicon (OEMs and end customers) are fuc*edup forever with an old, and unsupported, kernel - at least rebasing the BSP on the latest kernel version fo the same series gives you security fixes for free (that's what i was really looking for) - blame freescale that didn't rebase the imx6 BSP continuosly, and blame them some more for not pushing their bits upstream.

Anyhow, i'll send another pull request for master.

**Comment by piso77** [comment]
new pull:

https://github.com/OpenELEC/OpenELEC.tv/pull/4036

**Pull request closed without merging**
