### PR TITLE
projects/imx6/patches/linux: udoo dt - serial console on ttymxc0

### PR DESCRIPTION
**Pull request by vpeter4**

### CODE REVIEW

**Comment by lrusak** [comment]
do you want to enable serial console by default? or just have the option available?

**Comment by vpeter4** [comment]
Just to have it available. If set in uEnv.txt you get console messages and shell at the end.
Same as with RPi.

**Comment by lrusak** [comment]
Why don't you have the #4391 included in this PR?

**Comment by vpeter4** [comment]
This is udoo related PR and #4391 is generic for imx6.

**Comment by lrusak** [comment]
Gotcha, I'm still half asleep.

Have both PRs been runtime tested?

**Comment by vpeter4** [comment]
Yes, on Udoo and CuBox-i for months.

**Pull request merged**
