### PR TITLE
xf86-video-ati: use DRI3

### PR DESCRIPTION
**Pull request by lrusak**
I'd like to test this out, not sure if there is any negative impact

see, http://www.phoronix.com/scan.php?page=article&item=radeon-dri3-perf&num=1

```
grep -i dri3 /var/log/Xorg.0.log
```
should show something similar to:
>[1550498.698] (**) RADEON(0): Option "DRI3" "on"
>[1550498.864] (**) RADEON(0): DRI3 enabled

### CODE REVIEW

**Comment by Klojum** [comment]
Result on AMD A4-5300:
[1567747.349] (**) RADEON(0): Option "DRI3" "on"
[1567747.627] (**) RADEON(0): DRI3 enabled
No visible negative impact when enabled.

**Comment by fritsch** [comment]
Guys your mesa is built with:
```
--enable-dri \
 --disable-dri3 \
```

What impact did you think of?

**Comment by lrusak** [comment]
hmmm not sure how I didn't see this. 

xorg-server is built with dri3 support already.

**Comment by fritsch** [comment]
And also take care: intel ships with dri3 off by default as they have sever bugs in the dri3 chain, via: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1401784

**Comment by lrusak** [comment]
Yea I'll leave it off for intel. I don't have intel hardware to test with so that's not my territory.

**Comment by sraue** [comment]
please hold this back until OE 8.0, i had seen problems with dri3 in the past (intel gpu), thats why its still disabled (and yes i think it was a problem in mesa, so we cant enable this for other gpus)

**Pull request closed without merging**
