### PR TITLE
Replaced XBMC with Kodi

### PR DESCRIPTION
**Pull request by robbie0630**

### CODE REVIEW

**Comment by fritsch** [comment]
@robbie0630 any special intention to spam us?

**Comment by robbie0630** [comment]
@fritsch No, I just haven't used Git in a while, and I keep setting my global settings wrong. I created a test repository, and I got it working. The next request should be the last.

**Comment by fritsch** [comment]
You send emails to some twenty developers with every action you do on that PR. Btw. next time don't close it, rather force push the existing branch.

**Comment by robbie0630** [comment]
@fritsch Sorry. I code independently, and have absolutely no idea how an organization works.

**Comment by fritsch** [comment]
This has nothing to do with our "organization". It's the git basics :-)

In short: Don't close and open another PR if you need to change some things in your other PR.

**Pull request closed without merging**
