### PR TITLE
Fixes XBMC freezes after suspend when using MySQL

### PR DESCRIPTION
**Pull request by verybadsoldier**

### CODE REVIEW

**Comment by lrusak** [comment]
Is this still relevent?

**Comment by mkortstiege** [comment]
Should be submitted upstream if valid. Not commenting on the actual patch.

**Comment by verybadsoldier** [comment]
Problem is still there in current OpenELEC. I am maintaining a forked version of OE which include the patch:
http://openelec.tv/forum/112-mysql-setup/66482-xbmc-freezes-after-suspend-when-using-mysql?limitstart=0

**Comment by stefansaraev** [comment]
@mkortstiege https://github.com/xbmc/xbmc/pull/3175

**Comment by chewitt** [comment]
I'm closing this down because this kind of thing needs to be done upstream. I appreciate that your first attempt at changing things upstream wasn't accepted. Time has passed though, so maybe revisit with Kodi devs if this is still an issue for you. Thanks.

**Pull request closed without merging**
