### PR TITLE
libressl: update ca-cert bundle

### PR DESCRIPTION
**Pull request by lrusak**
The old bundle was from 2011.

Thanks @stefansaraev 

I have also included a bump for libressl.

This should be picked for openelec-6.0 also

### CODE REVIEW

**Comment by stefansaraev** [comment]
you may remove packages/security/libressl/cert/certdata.txt - thats not used at all.

**Comment by lrusak** [comment]
updated :+1:

**Comment by stefansaraev** [comment]
why bump ?

**Comment by lrusak** [comment]
because newer is better?

but for real, libressl 2.2.2 removes support for sslv3

**Comment by stefansaraev** [comment]
> because newer is better?

did soname change? api/abi changes? anyone? if you are going to push this to OE6. you will fail.

I wont play this game anymore. do whatever you want.

**Comment by lrusak** [comment]
updated and removed libressl bump

**Comment by MilhouseVH** [comment]
This change seems to be responsible for Pandora no longer working:

http://xbmclogs.com/pvo9hrqda (line 973)

[forum confirmation](http://forum.kodi.tv/showthread.php?tid=231092&pid=2174761#pid2174761)

**Comment by InuSasha** [comment]
seems the same like here: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1014640
post 13 may be helpful

**Comment by MilhouseVH** [comment]
If there is no easy fix, should this at least be reverted for the time being as it's not been a positive change, and the old bundle didn't seem to be causing any problems (unlike the new bundle).

**Comment by InuSasha** [comment]
in the old bundle are invalid RootCAs, so this is dangerous...
A quick fix (and dirty one) is to add the cert.
An other solution can be, to switch to an other bundle (from mozilla for example)

my theoretical 2cents,
Sascha

**Comment by lrusak** [comment]
@MilhouseVH can you test this again? it seems that it was cause by a misconfiguration on pandoras side. See, https://github.com/mcrute/pydora/issues/27

**Comment by MilhouseVH** [comment]
I'll ask the users that were reporting the problem for an update.

**Comment by MilhouseVH** [comment]
#4498 fixes this.

**Pull request merged**
