### PR TITLE
revert some imh meh

### PR DESCRIPTION
**Pull request by stefansaraev**
@sraue @fritsch

### CODE REVIEW

**Comment by fritsch** [comment]
I have no idea what the firmware does. Perhaps it's good, but I know for sure vivante v5 looses display / window ptrs and this is known since longer. 

I was warned by @mk01 months ago. Tested that over the long weekend ... it's a no go. Every second refreshrate switch we end up with black screen + menu sounds.

**Comment by stefansaraev** [comment]
k. dropped the firmware revert. ready to go. merging in 48 hrs if no objections.

**Comment by stefansaraev** [comment]
@fritsch ca4344d is reverted. do you still want this in (imx-vpu as before) ?

**Comment by fritsch** [comment]
I will rebuild when I find time. I want that the Adjust Refreshrate stuff does not leave us with blackscreen anymore. One of those driver bumps has fault in the blob, which forgets egl ptrs.

No idea which one exactly. But bumping of drivers was not needed at all - I did not even see a changelog.

**Pull request closed without merging**
