### PR TITLE
wetekplay "fixes"

### PR DESCRIPTION
**Pull request by stefansaraev**
@Memphiz saradc is meh. wrong values and nobody working on it. should go

@codesnake @sraue 4916d8c ended up in master by accident ? it introduces a regression - massive livetv stuttering. this revert was in my builds for long

### CODE REVIEW

**Comment by codesnake** [comment]
@stefansaraev I agree that temperature reported is wrong. But if you drop support for saradc, you can drop also the following patch: https://github.com/OpenELEC/OpenELEC.tv/blob/master/projects/WeTek_Play/patches/kodi/0004-Add-support-for-retrieval-of-CPU-temperature-on-Amlo.patch

**Comment by Memphiz** [comment]
Someone from wetek said they wanted to ask about the right adc values at amlogic. But thats long ago. Agree - if nobody fixes it it could go - i don't care about temperatures at all ;)

**Comment by stefansaraev** [comment]
@codesnake thanks. I missed that patch.

**Comment by stefansaraev** [comment]
@codesnake I am going to merge this tonight. any comment on wetekdvb from your side? iirc, this particular version caused some issues on nand installs, but we dont support nand installs in master (it's separate "wetek" branch). do you agree with reverting it ?

**Comment by codesnake** [comment]
@stefansaraev Yes I agree to revert the module. I tested it and it works good.

**Pull request merged**
