### PR TITLE
remove package: tvheadend

### PR DESCRIPTION
**Pull request by stefansaraev**
we cant support this anymore. time to move to unofficial.

### CODE REVIEW

**Comment by stefansaraev** [comment]
added to unofficial. will merge this and pick for 5.0 in 48 hours if no objections. then Ill build and upload to unofficial repos.

**Comment by ksooo** [comment]
@stefansaraev how do I build oe unofficial repo myself, btw?

**Comment by stefansaraev** [comment]
it's a submodule

in yout local OE git tree:
```
git submodule init
git submodule update
cd packages/unofficial
git fetch
git pull
```
sometimes git pull fails in packages/unofficial, depends on your git version. if it fails: "git checkout master; git pull" again

then use scripts/create_addon

**Comment by ksooo** [comment]
thx.

**Comment by prilly** [comment]
Why is support for tvheadend removed?

**Pull request merged**
