### PR TITLE
libcec: update version to 3.0.1, update to secure links, fix #4294

### LINKED ISSUE #4294: Openelec 5.95.3 - CEC loose connection with LG TV - (libcec 3.0.1 seems to solve the issue)
Hello,
I'm using Openelec 5.95.3 on my Raspberry Pi 2 and I have some trouble with CEC. I have a LG TV and it's working fine with a fresh boot. But after two days of inactivity, the Raspberry can't be seen anymore by the TV, so I have to reboot the Raspberry every time I don't use it too often.
After investigating, I found that libcec 3.0.1 solve this bug. So I installed an Openelec testbuild with libcec 3.0.1 and all was working ok. (http://forum.kodi.tv/showthread.php?tid=231092&pid=2044074#pid2044074)
I just installed Openelec 5.95.4 but I expect the same behavior, so could you update libcec version in the next beta?
Thanks in advance
Tillstaff

### PR DESCRIPTION
**Pull request by qods**
Thanks lrusak for showing your changeset https://github.com/lrusak/OpenELEC.tv/commit/b2859b6b594adfef99d46b4ce44b5f057b02fc8f

### CODE REVIEW

**Comment by stefansaraev** [comment]
as you continue to ignore me, see here https://github.com/Pulse-Eight/libcec/issues/132

**Comment by vpeter4** [comment]
qods, why do you push some other people commits? I think this person is capable to send PR himself.

**Comment by lrusak** [comment]
@qods Thank you for your enthusiasm but unfortunately libcec 3.0.1 is broken, we need to wait for 3.0.2.

**Comment by qods** [comment]
@vpeter4 
Because @lrusak told so here: https://github.com/OpenELEC/OpenELEC.tv/pull/4319

@lrusak @stefansaraev 
Okay. I made this PR because the segfault bug https://github.com/Pulse-Eight/libcec/issues/132 is about ubuntu not openelec. Here its been tested and working on openelec: https://github.com/OpenELEC/OpenELEC.tv/issues/4294
Its written: "So I installed an Openelec testbuild with libcec 3.0.1 and all was working ok"

But ok, i will make a new PR when something newer then 3.0.1 is been released.

**Pull request closed without merging**
