### PR TITLE
Add amdgpu support

### PR DESCRIPTION
**Pull request by lrusak**
This is based on top of #4386 after that PR is merged I will rebase as this requires linux 4.2+
 
I have added the amdgpu kernel driver to the kernel config and the firmware files in a separate commit. This can be seen [here](https://github.com/lrusak/OpenELEC.tv/commit/a1b692e6dd83d4ff3374a257a5d54a62dfcc35ec)

The amdgpu driver is still in it's infancy but why not support it as it develops.
more info about what this driver supports is here http://xorg.freedesktop.org/wiki/RadeonFeature/

If there is anything else that is missing please let me know.

I hope the mesa bump doesn't negatively effect any other gpu's (ie. intel).

### CODE REVIEW

**Comment by stefansaraev** [comment]
isn't amdgpu all about catalyst ? do we want catalyst back ?

**Comment by fritsch** [comment]
Nope. It's the new open source driver for new amd hardware. It is needed and wanted :-).

**Comment by sraue** [comment]
please use the updated license headers (without fsf adress, updated date (2014) see tools/mkpkg/mkpkg_xf86-video-amdgpu)
please dont use the brackets "[xyz]" instead use : "xyz:"

**Comment by sraue** [comment]
also use this format: "mesa: update to mesa-11.0.3" thats because i remove "mesa:" in release notes but use the commit list

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/4d6bf4e3acce2288de3379dd8a48343c1b862aa3 https://github.com/OpenELEC/OpenELEC.tv/commit/a454250a4946dc232e62e0ac8fbae69c7216e04b https://github.com/OpenELEC/OpenELEC.tv/commit/d9e20305cb2d0ad19d2b93d1efd5e99d1c530846

**Comment by lrusak** [comment]
@sraue as noted in the PR message you need lrusak/OpenELEC.tv@a1b692e6dd83d4ff3374a257a5d54a62dfcc35ec as well.

**Pull request closed without merging**
