### PR TITLE
Delete linux-999.04-revert-xhci-Set-scatter-gather-limit.patch

### PR DESCRIPTION
**Pull request by trsqr**
Kernel 4.0 has the following patch included which should make this patch unnecessary:
http://lkml.iu.edu/hypermail/linux/kernel/1503.1/04331.html

### CODE REVIEW

**Comment by stefansaraev** [comment]
hopefuly. @fritsch your opinion? I am for removing it.

**Comment by fritsch** [comment]
No oppinion. Users that are affected (not me) should test. ping @zag
@notathome

2015-04-29 15:18 GMT+02:00 Stefan Saraev <notifications@github.com>:

> hopefuly. @fritsch <https://github.com/fritsch> your opinion? I am for
> removing it.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/4114#issuecomment-97422705>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by trsqr** [comment]
Here's a test build if someone with this issue could test:
http://trsqr.net/olli/OpenELEC-Generic.x86_64-devel-20150429183334-r20728-g094273a.tar

**Comment by CvH** [comment]
ping @nicoh88 this should trigger https://github.com/OpenELEC/OpenELEC.tv/issues/3833 again

**Comment by sraue** [comment]
will merge this patch the next hours if no one complains

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/aa23f67652c910ad0edc47db05e3a22d9fb4533a thanks much

**Comment by the-dreamer** [comment]
My USB Tuners 461e have problems again on USB3 with 6.0 Beta 1.

**Comment by fritsch** [comment]
I asked you all to test this before it is merged. Please can someone provide a testbuild to @the-dreamer and see if it cures the issue, please?

**Comment by the-dreamer** [comment]
Okay before it will be a big issue. After answering here i have thought about this again. My USB Tuners were connected to USB3 Ports. The last recordings have this described issue. But yesterday i was watching "Das Erste" live and currently i am not sure if i have seen this issue. But on Sky, which i have recorded some movies i have this issue. My rpi which get the stream from the "Main" pc has also this issue on live tv. Yesterday i have switched back to usb2 port but have not watch tv since then. So after end of my thoughts i have maybe some issue with encrypted tv stations since last VNSI update (last commits have handled something with it... ). I could make some logs. but i need to know which log could help. So maybe until now i don't need a test build.

**Comment by fritsch** [comment]
Your issue is not related to the original USB issue. Open a new bug. Vnsi lately change the priority enumeration on the client. Change Priority once to -99 and then back to -1, restart and revisit.

**Pull request closed without merging**
