### PR TITLE
linux: switch to linux-4.1 for generic/legacy

### PR DESCRIPTION
**Pull request by stefansaraev**
replaces #4165

dont merge yet.

### CODE REVIEW

**Comment by stefansaraev** [comment]
@fritsch fyi there will be rc8. so waiting one week more :)

**Comment by fritsch** [comment]
Fine with me. Thanks much. I have no problem with pushing rc8, but let's release the new beta with 4.1 stable.

**Comment by stefansaraev** [comment]
updated to rc8. @sraue should we push this now for testing or wait one more week ?

**Comment by sraue** [comment]
@stefansaraev we can push for now, @popcornmix you have time to port the patches already? btw this should be a LTS kernel, we need the patches rebased on every 4.1 release

**Comment by popcornmix** [comment]
Should be done soon. I've started cleaning up the patches in preparation. I've ping you when it's ready.

**Comment by popcornmix** [comment]
@sraue rpi-4.1.y is available in the usual place. Was in last night's Milouse build without any obvious issues.

**Comment by sraue** [comment]
@popcornmix thanks much

**Pull request merged**
