### PR TITLE
curl: revert to 7.37.1

### LINKED ISSUE #3866: curl/thumbnails problems via FTP in openELEC 5.0.1
Hi.

After update of the curl in openELEC 5.0.1, the Thumbnails download via FTP is not working anymore.
Here the advancedsettings.xml:
```
<?xml version="1.0" encoding="UTF-8" ?> 
 <advancedsettings>
   <ftp>
     <remotethumbs>true</remotethumbs> 
   </ftp>
 </advancedsettings>
```

It look like the problem came into openELEC when going from curl 7.38.0/7.39.0 to version 7.40.0 !!!
Here my kodi.log file, from last openELEC 5.0.1 official build: http://pastebin.com/22K5hhkJ

Can anyone help ?

Thanks and best regards.

### PR DESCRIPTION
**Pull request by stefansaraev**
This reverts commit 03d43b3abed539df0dc9fa56bec947607868930f.
This reverts commit 9297b047a27ec6192bbec99dbb6280a5182233cc.

stick with what ubuntu ships, and bump it only if bumped in kodi depends

### CODE REVIEW

**Comment by stefansaraev** [comment]
@sraue I'd like to hear your ack here first.

**Comment by fritsch** [comment]
Let us stay calm and wait for: https://github.com/OpenELEC/OpenELEC.tv/issues/3886

I will provide a build with master + 7.37.1, then we will see.

**Comment by fritsch** [comment]
The other issues was _not_ libcurl related. But as we don't have any issue reports with 7.37.1 but some (Millhouse thread) + our own github issues - let's keep that in sync with Ubuntu please.

So +1 from me here.

**Comment by stefansaraev** [comment]
will merge this in 48 hours if no objections. and will also revert 5cc415e4d8f572d12ab6a567bd52154b0da9b0bc

ping @sraue 

ref #3900

**Pull request merged**
