### PR TITLE
Linux: update to 4.4-rc5

### PR DESCRIPTION
**Pull request by lrusak**
Thanks @fritsch for doing all the work.

There are a few patches that need to be fixed or dropped:
 - ~~linux-063-xpad-fix_xbox360_wireless.todo~~
 - linux-221-ngene-octopus.todo
 - ~~linux-950-saa716x_PCIe_interface_chipset.todo~~

### CODE REVIEW

**Comment by fritsch** [comment]
You are welcome - there was no work involved ... everything straight forward and all external drivers still build.

**Comment by sraue** [comment]
please remove: patch 56, 57, 58, 62 from rpi support patch (rtl8192cu/ August dvb related things)

**Comment by lrusak** [comment]
@popcornmix said my patches looked ok before. Mangling them to pick out certain commits will make it difficult to remake them in the future.

We build an out of tree rtl8192cu anyway and the august dvb commit just adds a couple device ID's

I see no harm in leaving them in.

**Comment by vpeter4** [comment]
I fixed linux-950-saa716x_PCIe_interface_chipset.patch. Will send PR after this is merged.

**Comment by lrusak** [comment]
Updated with fixed linux-950-saa716x_PCIe_interface_chipset.patch
I added support for this to Generic and Nvidia_Legacy

Thanks @vpeter4

**Comment by lrusak** [comment]
ping @MattDevo for the xpad patch

**Comment by lrusak** [comment]
Added MattDevo's thermal patches and xpad patch

**Comment by sraue** [comment]
@lrusak i always have removed this patches in the past we use the out of tree driver and the august dvb patch should be applied to all builds (which dont have this already in the kernel)

**Comment by lrusak** [comment]
@sraue done

**Pull request merged**
