### PR TITLE
kodi-pvr-addons: update to kodi-pvr-addons-4854fbe

### LINKED ISSUE #3790: PVR causes CEC reset loop
Hardware: IMX6/CuboxTv with Samsung TV. Separate Mythtv backend running 0.27

After upgrading to 5.0.0 I am encountering the following:

Once I enable live TV (mythtv PVR add-on) the CEC status seems to reset and cause the XBMC to restart. I have tried disabling CEC on all devices and still run into the same problem. Essentially I am unable to enable liveTV without XBMC restarting after about 10 seconds. This behavior is independent of the connected hardware. Any help would be greatly appreciated

### LINKED ISSUE #4045: OE 5.0.6 - Pi 2 - MythTV PVR addon crashes/freezes Kodi on EPG import
Hello,

All the setup (MySQL DB for videos and music, NFS shares for sources) goes well until I turn on the MythTV addon, then it has issues when importing the EPG, goes into a loop, until Kodi freezes (system up and accessible I can kill kodi through SSH).

I have the EXACT same setup on a Pi 1 B+, exact same setup/config, a carbon copy outside of the host name, and zero issue.

The power supply is a 2.0 A from The Pi Hut, presumed good. No rainbow square at any time.

It was like that on OE 5.0.5. I do not know how it was before.

The Kodi logs are pretty non indicative, no shouting outside of channel logo files that do not exist, same as the Pi 1.

I'm ready to go through the necessary effort for debugging and providing more info.

OE forum thread:
http://openelec.tv/forum/124-raspberry-pi/76116-rpi-2-unstable-mythtv-makes-it-more-visible

Thanks!

Nico

### PR DESCRIPTION
**Pull request by stefansaraev**
myth was updated upstream. should fix RPi2 crashes

mysql is no more.

this may fix #3790 
this may fix #4045

anyone with near-ready RPi2 build env can make testbuild for @camelreef @c00ntact

@sraue @fritsch

### CODE REVIEW

**Comment by camelreef** [comment]
I'm using MySQL for Kodi, not MythTV. 

If given the right git checkout, I can build myself,test and report. 

I managed to find the previously used patch and building right now. A Ctrl-Alt-fleche is easy enough! 

Thanks! 

Nico

**Comment by camelreef** [comment]
Ctrl-C... Stupid autocorrect on the phone...

**Comment by stefansaraev** [comment]
```
git checkout origin/openelec-5.0 -b openelec-5.0
wget https://github.com/OpenELEC/OpenELEC.tv/pull/4046.patch
git am < 4046.patch
PROJECT=RPi2 ARCH=ARM make release
git reset --hard HEAD~1
```

my "mysql is no more" comment has nothing to do with you using mysql. it's about mysql dependency is not required for kodi-pvr-addons anymore, as myth dropped the requirment.

**Comment by camelreef** [comment]
OK for mysql, I thought along those lines. 

I'll be checking out, patching and building as soon as I get back home. 

Give me a few hours before a report!

**Comment by camelreef** [comment]
Build based on above process available here for others to test. 

http://youplala.net/~nico/kodi/OpenELEC-RPi2.arm-devel-20150326210006-r20131-g9aa7b4c.tar

I have to wait for my SO to finish watching TV before I can test!

**Comment by camelreef** [comment]
OK, rebooted with this build, and it's looking very good so far! It has my positive vote.

Many thanks!

**Comment by stefansaraev** [comment]
thanks @camelreef

**Pull request merged**
