### PR TITLE
projects/imx6/patches/linux: fix driver for st1232 touchscreen

### PR DESCRIPTION
**Pull request by vpeter4**
it can work as singletouch or multitouch
in singletouch mode added touch button event

### CODE REVIEW

**Comment by stefansaraev** [comment]
since when we want to offer touichscreen support ?

**Comment by vpeter4** [comment]
From now in unofficial way. It is not enabled by default so doesn't brake anything.

**Comment by sraue** [comment]
is this some commit which is already added upstream?

**Comment by vpeter4** [comment]
No. It's my work.

**Comment by vpeter4** [comment]
Maybe I should make new module named st1332 which is one newer version?

**Comment by sraue** [comment]
can you find out how you can provide this upstream? i would add this, but it should be upstreamed midterm

**Comment by vpeter4** [comment]
From what I saw there is no real interest in such stuff to be supported. Not with Solidrun's kernel, not in Jon Nettleton's.
If you don't like it I will just apply it myself after cloning the repo. No big deal but would be nice to have it in.

**Comment by fritsch** [comment]
At least PR it upstream, this will help us in the future.

2015-06-04 12:18 GMT+02:00 Peter V. <notifications@github.com>:

> From what I saw there is no real interest in such stuff to be supported.
> Not with Solidrun's kernel, not in Jon Nettleton's.
> If you don't like it I will just apply it myself after cloning the repo.
> No big deal but would be nice to have it in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/pull/4180#issuecomment-108827049>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by vpeter4** [comment]
What's the point? I already closed one other PR after 6 months. Because it's obviously outdated.

**Comment by fritsch** [comment]
The point is: Nobody of us wants to manage and maintain valid fixes here downstream, cause such things belong upstream and come back from there again.

**Comment by vpeter4** [comment]
Why nobody? It's my thing and I will maintain it.
I would push all my changes for different imx6 systems upstream but there is no interest. I tried and failed.

**Comment by fritsch** [comment]
Mmh, you know what I would normally suggest with hardware, upstream does not care about?

**Comment by fritsch** [comment]
But yeah, go ahead. But please - the very moment, you don't feel like doing upstream's work anymore - tell me, so we can define the exit strategy.

Nothing wrong with the work and time you put into this. But don't get yourself burned out by upstream, please.

**Comment by vpeter4** [comment]
Mhm, then we can remove all other patches in linux folder because there is support for some other hw too.
Second part I don't understand.
Anyway, it's not my decision to include it or not. I prepare it and I will used it.

**Comment by stefansaraev** [comment]
> Mhm, then we can remove all other patches in linux folder because there is support for some other hw too.

be careful what you say. and to whom, please. 

other patches are about hardware that we support. we do support dvb-t sticks, and wifi sticks, and what not for years. we never supported touchscreens, and we dont want to. that was made clear 10 times in past one year..

however, I am not against this. to be honest, I dont care about your "unofficialy officialy supported imx6 boards".

up to @sraue . hell merge the sh** out and be done with it. end of drama.

**Comment by fritsch** [comment]
> Also why do we have linux-999-3.14-vpu352.patch? It belongs to solidrun's kernel at least.

Verified and talked with solid-run. Needed to play livetv. Without it - you cannot even decoder 1080p30 without hickups.

**Comment by vpeter4** [comment]
I was not talking about support them but about having patch which should go upstream. For example linux-250-fix-dvbsky.patch.
And yes, this is my last message in this PR.

**Comment by stefansaraev** [comment]
dvbsky patches are already upstream. all of them sent to mainline by the author.. stop spreading nonsense. thanks.

**Comment by fritsch** [comment]
@vpeter4 I really don't understand why you always, with every PR search for trouble. I only try to help. Also I don't get at all why you want to "park" patches here in OpenELEC for platforms / hardware we don't support at all.

To make that fully clear: We don't support touchscreens and until we do - this patch has absolutely nothing to do in this repository.

**Comment by vpeter4** [comment]
Just one more thing to seo about my "unofficialy officialy supported imx6 boards". It all starts very officially last year between Udoo and sraue. Which obviously you don't know. I'm just continuing work I committed to. Similar story to Wetek Play. But one got much bigger attention.

**Comment by stefansaraev** [comment]
then it seems, it was not worth informing me. at all. and so is nothing more than unofficialy-blabla.

**Comment by vpeter4** [comment]
Already in discussion with original author.

**Comment by stefansaraev** [comment]
who deleted my comments here ?

**Comment by stefansaraev** [comment]
so. noone from the team has an idea what happenned to my comments here? (and not only mine, btw)

**Comment by fritsch** [comment]
mine are also missing ...

**Pull request closed without merging**
