### PR TITLE
curl: Describe why we want it stable

### PR DESCRIPTION
**Pull request by fritsch**
@CvH

### CODE REVIEW

**Comment by stefansaraev** [comment]
I hope he is happy now. I'll pick for master.

**Comment by CvH** [comment]
@fritsch
yea great, at least some kind of benefit for your wasted time with the curl bump. 
These descriptions should be standard if these kind of information/bugs are available, should safe some time at the next bump.

**Comment by fritsch** [comment]
They also should be standard when bumping versions within a stable release.

**Comment by stefansaraev** [comment]
@CvH there is almost noo benefit for his and my wasted time. only white hair. but thanks for your comments :)

btw, where have you been in past xx weeks ?

there will be no next bump

**Pull request merged**
