### PR TITLE
device type for cec is now Player instead of Recorder. This way it is…

### PR DESCRIPTION
**Pull request by gdachs**
… matching with the announcement of u-boot. Thanks to kszaq!

### CODE REVIEW

**Comment by kszaq** [comment]
I don't think this should be changed for WeTek Play as it doesn't have CEC enabled in u-boot and if we keep "Player" device type, more buttons can be sent from TV's remote, e.g. numbers and CH-/+. This is desirable considering the fact that most users use WP with DVB tuners and want to change channel numbers using TV's remote.

I don't have a WeTek Core to comment on it.

**Comment by gdachs** [comment]
you mean to keep **recorder** device type on the play? Yes, I can change this back. I didn't now that it is not enabled in the play.

**Comment by kszaq** [comment]
Yes, I think it's better to keep it as **recorder**. As for WeTek Core - I don't know, don't have a device. Does it offer wakeup over CEC?

**Comment by gdachs** [comment]
Shit, I have thought you told me that there is a problem with cec wakeup because the device type is different between u-boot and kodi. Have forgotten who it was then. Sorry, I am old. 
But I know for sure that it was a core, I only changed it for the play because of symmetry ;)

**Comment by kszaq** [comment]
It was me. :) I actually told you of the change needed for S805 devices to make your driver fully work according to my needs.

**Pull request merged**
