### PR TITLE
linux: update to linux-4.3.2

### PR DESCRIPTION
**Pull request by MilhouseVH**
I'll be honest, I have no idea what 4.3.2 (or even 4.3.1) brings but downstream projects (raspberrypi/linux/rpi-4.3.y, fritsch) are already ahead of OE master so...

### CODE REVIEW

**Comment by lrusak** [comment]
Should be fine, do you want me to update the RPi patches?

**Comment by MilhouseVH** [comment]
Yes, that would be great. We'll also need the following RPi/RPi2 config options added once you merge the latest RPi kernel patches:

[Enable i2s](http://nmacleod.com/public/oebuild/patches/00_kernel_4_3.txt) - needed by i2s audio cards
[Drop ATAGs support](http://nmacleod.com/public/oebuild/patches/00_kernel_4_3_ATAG.txt) -  see https://github.com/raspberrypi/linux/pull/1178
[Configure extra touchscreen](http://nmacleod.com/public/oebuild/patches/00_config_430_touch.txt)

with the following deleted (no longer needed):

projects/RPi/filesystem/usr/lib/modules-load.d/bcm2708-rng.conf
projects/RPi2/filesystem/usr/lib/modules-load.d/bcm2708-rng.conf

Do you want a separate PR for the above 5 changes, or better to integrate them into the one update with kernel changes?

**Comment by lrusak** [comment]
Please pick 
lrusak/OpenELEC.tv@e63a255070cedbd12e2eaccaa84be6f83b53cffc
lrusak/OpenELEC.tv@92a819ef521080e3afb644d96154b6a3c6f7eb13
lrusak/OpenELEC.tv@c566936419911f19189f8b3a8d9e89825abf5611

**Comment by lrusak** [comment]
@MilhouseVH please see above comment

**Pull request merged**
