### PR TITLE
systemd-addon-wrapper: make binary addons executable ...

### PR DESCRIPTION
**Pull request by vpeter4**
... before starting service

### CODE REVIEW

**Comment by stefansaraev** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/patches/kodi-100.05-make-binary-addons-executable.patch should be enough, but this PR does not hurt. OK from me.

**Comment by vpeter4** [comment]
Actually patch you mention doesn't help in this case. Seems service is started before files get executable permissions.

**Comment by lrusak** [comment]
:+1: thanks for this vpeter

**Comment by stefansaraev** [comment]
oh, I thought you forgot about the kodi patch. well as said :+1: push it.

**Comment by vpeter4** [comment]
I checked the file xbmc/addons/Addon.cpp and how we set executable permissions there. I think it should be enough to set permission at top of function OnPostInstall() before actions for service addons are executed. Then chmod inside our wrapper would not be needed.
But even with current state nothing is wrong.

**Comment by lrusak** [comment]
@sraue please pick for openelec-6.0

**Pull request merged**
