### PR TITLE
kodi.sh: Do not overwrite kodi_crashlog.log, keep older crashlogs.

### PR DESCRIPTION
**Pull request by ksooo**

### CODE REVIEW

**Comment by stefansaraev** [comment]
we can end up with thousands of crashlogs. need something to clean up old..

**Comment by MilhouseVH** [comment]
Seems like this should have a limit, either based on number of logs (keep last 12?) or date (keep a weeks worth?) I had a system go into a crash loop unnoticed for several hours the other day - I'd have had hundreds of crash logs with this PR.

**Comment by stefansaraev** [comment]
```
rm -f $(ls -1t $CRASHLOG_DIR/kodi_crashlog_*.log | tail -n +11)
```

sorta.

**Comment by ksooo** [comment]
Kodi has more than one scenario where it bombs. ;-) Some (rare) crashes do actually occur if I'm not at home and my family uses the system. Collecting all the different(!) crashlogs gives me the chance to analyze them all at some point in time, not just the latest.

**Comment by ksooo** [comment]
Now keeps only youngest 10 crashlogs.

**Comment by ksooo** [comment]
@stefansaraev btw, where do the exit code definitions used in kodi.sh come from?

**Comment by stefansaraev** [comment]
@ksooo https://github.com/xbmc/xbmc/blob/master/tools/Linux/kodi.sh.in#L159

**Comment by stefansaraev** [comment]
I am fine with this now (10 crashlogs). @MilhouseVH ?

**Comment by MilhouseVH** [comment]
10 is good, I'm OK with that. Thanks both.

**Pull request merged**
