### PR TITLE
[systemd] update to track latest version

### PR DESCRIPTION
**Pull request by lrusak**
supersedes #4206 

For testing purposes only ;)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
> For testing purposes only ;)

What's the confidence level for this one - should I include it in a test build? :)

**Comment by stefansaraev** [comment]
@MilhouseVH 

> What's the confidence level for this one - should I include it in a public test build? :)

nope. not for "regular joe"

after quick test custom hwdb.d (in /storage/.config) is broken for me (no time to investigate atm). and, this wont be merged for OE6 anyway.

**Comment by MilhouseVH** [comment]
OK. I'm currently building Kodi master (Jarvis) on top of OE master, so if/when you think it's ready for wider testing please ping.

**Comment by stefansaraev** [comment]
ok. hwdb is functional. it was the rule format that changed. all users who use this feature. must update their rules

@lrusak pls pick and squash https://github.com/stefansaraev/OpenELEC.tv/commit/627dfe63c61eeb7f011260559ed52fda3dc3ac9e

**Comment by lrusak** [comment]
picked and squashed

**Comment by MilhouseVH** [comment]
Ready for wider testing? I gave this a quick spin (after the squash) on RPi2 and it seemed OK.

**Comment by stefansaraev** [comment]
if you do Jarvis builds - yes. should not be merged for Isengard.

**Comment by MilhouseVH** [comment]
@lrusak: Would you mind rebasing on master after 7f40ce7d9a7ca2711a129434d9cf331ec7d72f34? Thanks.

**Comment by stefansaraev** [comment]
https://github.com/stefansaraev/OpenELEC.tv/commit/47e9fd2109154945b317c37973d780d1596999c6

**Comment by lrusak** [comment]
@MilhouseVH done

**Pull request closed without merging**
