### PR TITLE
PHIREE U2 is upstream so no need for patching 

### PR DESCRIPTION
**Pull request by mrdominuzq**
http://git.alsa-project.org/?p=alsa-lib.git;a=commit;h=ea865bba4615d906144ae5d4f72a4aad2baffe1f

but im not sure USB Soundblaster HD works without the patch.

### CODE REVIEW

**Comment by stefansaraev** [comment]
@fritsch

**Comment by fritsch** [comment]
Jep +1 was done by @Anssih he knows what he is doing.

**Comment by stefansaraev** [comment]
@mrdominuzq could you please replace alsa-lib-USB_Soundblaster_HD.patch with a propper git formatted patch ?

**Comment by mrdominuzq** [comment]
done, is it correct ? :)

**Comment by stefansaraev** [comment]
yup. thanks much. mind squashing ?

**Pull request merged**
