### PR TITLE
Kodi 16.0 Jarvis

### PR DESCRIPTION
**Pull request by lrusak**
All required packages have been pushed to the ftp.

Please check for errors as this is a large PR.

### CODE REVIEW

**Comment by stefansaraev** [comment]
@codesnake amcodec bump ok? I am using this for 2 months and seems to be ok. there are no changes at all besides hevc fix (wetek has no hevc anyway) and firmware changes.

**Comment by codesnake** [comment]
@stefansaraev Sure

**Comment by MilhouseVH** [comment]
The binary addon packages are missing from the ftp server (pretty much all of them - audiodecoders, pvr, etc.).

**Comment by lrusak** [comment]
@MilhouseVH I just re-pushed them, try now :)

**Comment by MilhouseVH** [comment]
Looks like the adsp source packages are missing from the OE servers.

**Comment by MilhouseVH** [comment]
Is the deletion of `projects/RPi/patches/kodi/kodi-001-isengard-rpb-backports.patch` and `projects/RPi2/patches/kodi/kodi-001-isengard-rpb-backports.patch` intentional - I'm guessing not...

**Comment by lrusak** [comment]
@MilhouseVH these patches don't apply anymore so I dropped them for now.

**Comment by stefansaraev** [comment]
@lrusak pls also drop https://github.com/OpenELEC/OpenELEC.tv/blob/master/projects/WeTek_Play/patches/kodi/0102-enable_remoteaskeyboard_by_default.patch

the feature is gone in jarvis.

**Comment by lrusak** [comment]
Please ask before merging, there were some small changes I would have liked
to make.

**Pull request merged**
