### PR TITLE
vdr-wirbelscan: update to vdr-wirbelscan-0.0.9

### PR DESCRIPTION
**Pull request by stefansaraev**
this fixes crash in the middle of runing scan

two (new) upstream bugs fixed:
 - fix upstream bug where dvb-s scan scans only on
 first defined transponder frequency
 - allow using wirbelscancontrol plugin for manual scans

would be nice if someone can test dvbc/t/atsc

@gdachs fyi

### CODE REVIEW

**Comment by gdachs** [comment]
Thanks, will report upstream.

**Comment by stefansaraev** [comment]
@gdachs would be nice if you have time to test http://sprunge.us/Ddea

**Comment by gdachs** [comment]
I have only DVB-C and anyway no time before end of week, hopefully.

**Comment by stefansaraev** [comment]
all good.

**Pull request merged**
