### PR TITLE
kodi: update to kodi-14-e7ba06f

### PR DESCRIPTION
**Pull request by wezley98**
Update OpenElec 5.0.x to use Kodi 14.2 RC

### CODE REVIEW

**Comment by fritsch** [comment]
Thx - do all our custom patches still apply? Anything that can be dropped?

**Comment by stefansaraev** [comment]
wait for @sraue I am sure he already has it packaged and pushed to his local tree.

**Comment by wezley98** [comment]
Just running the build process now, am I correct in assuming that the build process would notify me on completion if anything failed to apply?

Note: Quite new to the project but do have spare time if there is anything that needs to be worked on, Mainly a php dev for coding skills, but I want to contribute something back to the project as I use it every day.

**Comment by fritsch** [comment]
Spare time is always good to have. Make yourself familiar with our buildroot. That way you will be able to provide (un)official addons. Furthermore there are a lot of users with very small questions on IRC - also welcome here to help.

**Comment by wezley98** [comment]
Will do.

Looks like this build fails to apply @ OpenELEC.tv/projects/RPi2/patches/kodi/kodi-001-helix_rpb_backports.patch

http://sprunge.us/jYeY

**Comment by stefansaraev** [comment]
added

**Pull request closed without merging**
