### PR TITLE
mt7610u: add driver package

### PR DESCRIPTION
**Pull request by chewitt**
Initial support for the mt7610u chipset to solve #3554 - I don't have one of these devices so please do not merge until we see some users on the issue report confirming it works.

### CODE REVIEW

**Comment by sraue** [comment]
dont like its pulled from a github repo dedicated for OE only with no real commits... better is to repack the original sources or use a repo which really fixes stuff in this driver... other then that we should search for overlapping pciids from in-kernel mt7601 driver

**Comment by sraue** [comment]
other then that it looks here like mediatek provides the same driver for MT7601 and MT7610... so if this driver comes from there we have to remove all MT7601 usb ids...

**Comment by chewitt** [comment]
The mediatek site shows mt7601u release notes and download links but Google shows plenty of reports from mt7610u users building the driver and complaining it doesn't work, as it's the wrong driver. Both are forked from the same original source so they look similar and mediatek are lazy for not combining them into a single package, but they are different and AFAIK there are no USB ID overlaps. The only mt7610u sources I could ever find were from TP-LINK and wouldn't compile, but it looks like our user patched it up to solve that. The driver is not OE specific and IMHO is no better or worse than anything else you can find. https://github.com/kuba-moo/mt7601u/issues/6 <= this is the author of the in-kernel mt7601u driver stating they are different.

**Comment by sraue** [comment]
is there another source then https://github.com/sohaib17/mt7610u which is a repo with 2 commits and done for openelec? whats the original source?

**Comment by chewitt** [comment]
http://www.mediatek.com/AmazonS3/Downloads/linux/mt7610u_wifi_sta_v3002_dpo_20130916.tar.bz2

MT website now has links to the ^^ original driver (but still shows wrong release notes). It appears to be the same driver our user put in his git repo. This needs patches to build on a current kernel. I asked the user for links to the patches changes they applied. NB: his repo was created for him to use on OE but it is not no an OE specific driver, it builds fine on Ubuntu as well.

**Comment by chewitt** [comment]
https://bitbucket.org/sanrath/mediatek_mt7610u_sta_driver_linux-64bit <= looks like a good source of patches for this driver. The only aspect of this driver that concerns me is the wireless config in the .dat file; commits show people making country-specific changes and OE should ideally have a 'one size fits all' configuration. I'll go back and have a look at what the mt7601u driver used before it was merged with the kernel.. as it's the same file used for the same purpose.

**Comment by chewitt** [comment]
I'll find time for this between 6.95.1 and 7.0.0 release. If it's going to be used as an excuse to delay the 6.95.1 beta I will close the PR and submit it again later.

**Pull request closed without merging**
