### PR TITLE
Fix 16bpp plymouth-lite patch which doesn't use stride consistently

### PR DESCRIPTION
**Pull request by MilhouseVH**
See https://github.com/OpenELEC/OpenELEC.tv/pull/4221#issuecomment-117840719

Thanks @popcornmix, @samnazarko

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks @MilhouseVH I'll do runtime test tonight

@fritsch the patch is fine ;)

**Comment by fritsch** [comment]
Okay, then in with it.

**Comment by stefansaraev** [comment]
all good. should we merge now or you wait for some more feedback @MilhouseVH ?

thanks again to everyone involved ;)

**Comment by fritsch** [comment]
Revert is always an option

**Pull request merged**
