### PR TITLE
add serial console support

### PR DESCRIPTION
**Pull request by haggaie**
Make debugging a raspberry pi simpler by adding agetty and a serial console service.

### CODE REVIEW

**Comment by stefansaraev** [comment]
I dont think so. this should be:

1. project specific.
2. avoid agetty if possible.

here is an example what I use on my wetek_play. http://sprunge.us/cBdT

**Comment by vpeter4** [comment]
Yes, this systemd thing stefansaraev posted works perfectly.

**Comment by haggaie** [comment]
I wasn't aware systemd could do that without agetty. Regarding being project specific, if you need it for WeTek, and I need it for Raspberry Pi, don't you think it would be helpful to have it somewhere in the common code?

**Comment by stefansaraev** [comment]
nope. because x86 wont need it. and I, personaly, keep it in my build tree, not upstream (regular joe does never debug anything)

**Comment by haggaie** [comment]
I'm new here so I might be talking nonsense, but how many regular joe's build there own image from source?

In any case, if I submit a pull request for (an optional) service file for Raspberry Pi only, would you consider it? I just want the next person that tries to debug something to find it more easily.

**Comment by stefansaraev** [comment]
> In any case, if I submit a pull request for (an optional) service file for Raspberry Pi only ...

of course I would (as long others agree)

**Comment by haggaie** [comment]
Okay, great :)

**Comment by haggaie** [comment]
A question: from what I understand, putting the service file in the project's filesystem dir would always install it. If I want to conditionally install it (when OPENELEC_VERSION=devel for instance), it has to be in a package, right? Or is there another way?
What would be the best way to do that?

**Comment by vpeter4** [comment]
I think this file could be always installed but started conditionally. Like using in service file
```javascript
ConditionKernelCommandLine="console=ttymxc1,115200"
```
I didn't have time to test this if really works. According to  stefansaraev it should. So only if console is set in boot params then service is started.

**Comment by haggaie** [comment]
Okay, I'll try that. Thanks.

**Pull request closed without merging**
