### PR TITLE
kodi: add patch to support keys on the rii mini i8+

### LINKED ISSUE #4401: Several keys of the Rii mini i8+ remote not working on 5.0.8 and 5.95.5
I guess fixing this on 5.95.5 is going to be the most pressing. The following keys don't work:
- search: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(217)
- home: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(144)
- weird circled play button: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(171)

### PR DESCRIPTION
**Pull request by lrusak**
fixes #4401 

should be picked for openelec-6.0 if there is time

### CODE REVIEW

**Comment by stefansaraev** [comment]
my 2 cents
thouse keys should really be defined as names not numbers. as in include/uapi/linux/input.h

KEY_FILE -> XBMCK_HOME
KEY_CONFIG -> XBMCK_POWER (really? this remote has "config" button that acts as poweronoff?)
KEY_SEARCH -> XBMCK_TEXT

**Comment by rtega** [comment]
Shouldn't a few new XBMCK-labels be added? There are so many remotes out there with special keys for which there is no label. I suggest XBMCK_MAIL, XBMCK_CONFIG and XBMCK_SEARCH in this case. These are common keys found on many remotes.

**Comment by stefansaraev** [comment]
> Shouldn't a few new XBMCK-labels be added

no.

**Comment by rtega** [comment]
Why not?

**Comment by stefansaraev** [comment]
because that has to be done upstream (in kodi). this patch should go upstream at some point too. thanks for the spam.

**Comment by lrusak** [comment]
Updated,

KEY_FILE was added in @4b5b447711bc2f7ca70b8df5611dd3c8bd0176ff
KEY_SEARCH was added in @481609c5a2297bb9a23916a9229e1caea2375cab

**Comment by rtega** [comment]
Thanks!

**Pull request merged**
