### PR TITLE
zip packages extraction fix

### PR DESCRIPTION
**Pull request by CvH**
should fix *.zip packages
before pr:
> PKG_NAME-PKG_VERSION.zip

creates
> build.OE.../PKG_NAME/PKG_NAME-PKG_VERSION/files*

instead of 
> build.OE.../PKG_NAME-PKG_VERSION/files*

### CODE REVIEW

**Comment by CvH** [comment]
updated PR with the change @vpeter4 proposed

**Comment by lrusak** [comment]
Looks ok to me. Should these packages be repackaged into tar.xz?

**Comment by CvH** [comment]
no, zip works fine (now)

**Comment by CvH** [comment]
@sraue ?

**Pull request merged**
