### PR TITLE
bump libcec & kodi

### PR DESCRIPTION
**Pull request by stefansaraev**
imx6 cec needs testing.

### CODE REVIEW

**Comment by stefansaraev** [comment]
removed imx patch, it needs complete rewok. seems PLATFORM::CCDevSocket is no more (stuff missing in libplatform?). thats beyond my skills.

**Comment by stefansaraev** [comment]
updated. requires https://github.com/Pulse-Eight/platform/pull/6

**Comment by sraue** [comment]
works here, please merge after https://github.com/Pulse-Eight/platform/pull/6 is in and before beta-2 (if its not in then we will add https://github.com/Pulse-Eight/platform/pull/6 as a patch)

**Comment by stefansaraev** [comment]
will take care :+1:

**Comment by sraue** [comment]
please add http://paste.fedoraproject.org/220249/00917143 (and squash), its needed (here) to not install libplatform.a to $SYSROOT_PREFIX/usr/lib64 where libcec cant find libplatform.a

**Pull request merged**
