### PR TITLE
projects/imx6: final merge of all changes

### PR DESCRIPTION
**Pull request by vpeter4**
tested on TBS Matrix v2.1 and CuBox-i4Pro

### CODE REVIEW

**Comment by vpeter4** [comment]
No more interest for imx6 and openelec?

**Comment by jpulz** [comment]
+1 for Wandboard (Quad Rev. B1 in my case)

**Comment by xoddark** [comment]
Wandboard support is not integrated to this pull request.
What is the best ? 
- merge this and made a second pull request for the Wandboard (and Udoo)
- or create a new pull request with the support for all the additional imx6 support.

**Comment by vpeter4** [comment]
I don't have Wandboard so I would prefer second PR for it.

**Comment by xoddark** [comment]
I wait for integration of this, and after I would do a Pull request for Wandboard management.

Thank you.
PS: Lakka project wait this to resurrect their Wandboard version.

**Comment by piotrasd** [comment]
+1

**Comment by vpeter4** [comment]
So I see OpenELEC 5.0.2 and still no sign of merging this PR. And I though this will be done after 5.0.0.
@sraue: is there any interest of OpenELEC to support more devices based on i.MX6 SoC or not? If yes then do it and if not then tell us so we can move on and stop waiting for official landing.

**Comment by piotrasd** [comment]
@vpeter4 could you rebase ? Thanks

**Comment by vpeter4** [comment]
@piotrasd: why waste time if not merged anyway.

**Comment by vpeter4** [comment]
I'm giving up on this so closing PR. To bad.

**Comment by CvH** [comment]
At least a short statement from @sraue should be doable :-(

**Comment by JoostK** [comment]
Please merge this so OpenELEC may benefit from the additionally support devices. @vpeter4 has done some awesome work here, I have been running his UDOO build for several months already without issues.

**Comment by fritsch** [comment]
@sraue A statement is needed if you want to have that integrated or not. Shipping and providing another 4 images is a completely different topic and from my POV unlikely to happen.

**Comment by sebguilbaud** [comment]
what to you mean by the "statement" term ? (french spoken here)
@vpeter4's work should not remained unused, it is not clean enough to be merged ?

**Comment by vpeter4** [comment]
@xoddark took over my work here: https://github.com/xoddark/OpenELEC.tv/commits/imx6_multi_devices
I will help him as much I can.
So support for other devices is on the way.

**Comment by RadiatorTwo** [comment]
I want to make OpenELEC run on the RIoTBoard.
I managed to compile and boot the version from @xoddark.
I used the mainline u-boot and dtb from mainline Kernel though. Boots up without problems and can get a picture in u-boot over HDMI.
But I can´t get a picture on when OpenELEC starts.

I´d like to integrate the needed code, but I´m no kernel/driver programmer and would need some help on what I have to change to make it run.
Only need the Info in what places I have to make changes.

**Comment by vpeter4** [comment]
You need to use appropriate dtb for kernel 3.14 which is used for imx6 project - in general you can't mix dtb's between different kernel versions. So you have 2 options: use mainline kernel or port required changes to kernel used by openelec.

**Comment by RadiatorTwo** [comment]
Ok then I´ll stick to the mainline kernel since all changes are in there.
Will only have to look on how to boot up the rootfs.
Thanks for the reply.

**Comment by MCOberle** [comment]
@RadiatorTwo Are you sure that the mainline kernel supports vpu and gpu?

**Comment by s00500** [comment]
Please merge this! @vpeter4's work is really cool and running Openelec on the i.mx6 is a really nice thing! I can't understand why this request hasn't been accepted yet

**Pull request closed without merging**
