### PR TITLE
xf86-video-nvidia: update to xf86-video-nvidia-352.79

### PR DESCRIPTION
**Pull request by MilhouseVH**
http://www.geforce.com/drivers/results/97645

### CODE REVIEW

**Comment by chewitt** [comment]
The release notes state this adds support for new GPU devices, so are there any udev rule changes needed? ..e.g. the list of device ID's that are used to select the non-legacy driver.

**Comment by MilhouseVH** [comment]
I don't know, is that something which runs as part of the build or is it a static list that needs updating with each new driver? I included this driver in my last Generic test build #0129:

http://forum.kodi.tv/showthread.php?tid=238393&pid=2229796#pid2229796

**Comment by chewitt** [comment]
packages/x11/driver/xf86-video-nvidia/scripts/make_nvidia_udev.py needs to be run to generate a new 96-nvidia.rules then diff against the existing file to see if there's anything new added.

**Comment by lrusak** [comment]
Yes, as @chewitt said. the [script](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/x11/driver/xf86-video-nvidia/scripts/make_nvidia_udev.py) needs to be run.

From the root OpenELEC directory you simply need to run it
```
python packages/x11/driver/xf86-video-nvidia/scripts/make_nvidia_udev.py
```
You made need some python packages in order to run it (python-lxml python-requests). It should be compatible with python 2 or 3.

**Comment by MilhouseVH** [comment]
Would it be possible for this python process to become part of the build, rather than for it to be run manually whenever something changes?

I've added a second commit to include the updated rules.

**Comment by lrusak** [comment]
Nope, as it pulls info from a website I'd rather not. It just needs to be run whenever the package version changes.

**Comment by MilhouseVH** [comment]
OK will try and remember next time. :)

**Comment by lrusak** [comment]
If you want to include a comment next to or above the PKG_VERSION to remember to run the script that would be great :)

**Comment by MilhouseVH** [comment]
How's that?

**Pull request merged**
