### PR TITLE
Oe6 update

### PR DESCRIPTION
**Pull request by sraue**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
It's a freaking maintenance release! :(

:-1:

**Comment by lrusak** [comment]
I'd rather not :-1:

**Comment by sraue** [comment]
look at the commits, 1/3 buildsystem fixes which dont harm the build, 1/3 package updates (minors and security fixes) and aml cec support... what you dont like? (most packages in sync with master, which already runs for many users without known complains)

**Comment by MilhouseVH** [comment]
Did you ever think about communicating this first with your team members?

**Comment by chewitt** [comment]
-100 from me .. not that it will make any difference

**Comment by sraue** [comment]
yes everytime... bugfix releases contains bugfix (x.y.Z) package updates, this we do since 6 years this way

**Comment by MilhouseVH** [comment]
Perhaps if it wasn't so last minute it would be easier to digest, the fact you don't communicate with anyone in the project and then drop this motherload of changes just makes it easier to walk away from this cluster fuck.

**Comment by MilhouseVH** [comment]
Are you censoring github now? Special.

**Pull request merged**
