### PR TITLE
Add visualization.vsxu

### PR DESCRIPTION
**Pull request by notspiff**
adds a vsxu based addon. had to climb a dependency tree..

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks.

minors:
https://github.com/stefansaraev/OpenELEC.tv/commit/31ce74d5d600c34f1341445b6194e0f35d9145d9

https://github.com/stefansaraev/OpenELEC.tv/commit/a0e0cc9f3e65d44e69cb0fa926acd377484f9a0a

**Comment by notspiff** [comment]
picked/squashed.

**Comment by stefansaraev** [comment]
hah, it seems openexr / ilmbase is not used at all @notspiff and I failed to notice while build testing :)

should I remove those ?

**Comment by notspiff** [comment]
they are used by one of the vsxu plugins, in particular plugins/src/texture/module_texture_load_openexr.h

ilmbase is a dependency of openexr.

**Comment by notspiff** [comment]
arr. indeed. seems openexr is unused, but the stupid buildsystem confused me. it should be safe to remove them.

**Pull request merged**
