### PR TITLE
update fuse-exfat to 1.2.0, dosfstools to 3.0.28, dbus to 1.10.0 and libusb to 1.0.20

### PR DESCRIPTION
**Pull request by qods**
Links and licences also updated

### CODE REVIEW

**Comment by fritsch** [comment]
@qods did you test the dbus bump? Does the OE addon still work? Is the conman integration still happy? Or did you only compile check?

-1 for OE 6.0 - this time it should not break just before release cause of package bumping game.

**Comment by fritsch** [comment]
Example: https://bugs.archlinux.org/task/46363?project=1&cat%5B0%5D=31&string=dbus

And future: No major bumps without testing!

**Comment by stefansaraev** [comment]
-1 on dbus bump for OE6. -1 on bumping anything (even minors) if those do not fix a known bug.

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/9a466be33c71f69cfe6ff38b49b1062142bd0283 https://github.com/OpenELEC/OpenELEC.tv/commit/adc71ae3f415b3129fcf212d18381d1c2c48e4c9 and https://github.com/OpenELEC/OpenELEC.tv/commit/d70062793766aea9bbe6b08ed905a6916f9d9d48 please create a own PR for dbus bump and follow our commit description scheme for future PRs

**Comment by qods** [comment]
Sorry. I had compiled an tested quick the dbus change. I have missed the broken OE addon loading service. As fritsch tought, yes, it does not work any more with dbus 1.10.0 .

**Pull request closed without merging**
