### PR TITLE
projects/WeTek_Play/patches/linux: Remove all NAND partitions in device tree

### PR DESCRIPTION
**Pull request by codesnake**
Having pre-defined NAND partition layout in device tree causes NAND driver to
update partition layout in NAND environment. If we are booting OE from SD-card
but have Android installed in NAND, this will overwrite Android NAND partition layout
with OE partition layout, and bootloader will no be able to boot Android anymore.

This update removes NAND partition layout from OE device tree. This causes NAND
driver to always use partition layout from NAND environment never overwriting it.

For OE NAND installations partition layout will be written to NAND environment
by recovery during installation, and then just reused by OpenELEC.

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks much. so after this we can re-add 06e5bdcf7890d0b7de709226a80403619eb4069d (assuming an android OTA with updated bootloader comes soon) ?

I'll re-test all tonight.

**Comment by codesnake** [comment]
Yes, I tested both with OE in NAND and Android + OE from SD-card. It seems works without problems. And also allows to access the Android partitions from OE.

**Comment by stefansaraev** [comment]
humh, any chance you can rebase if I update wetek branch ?

**Comment by codesnake** [comment]
ok

**Comment by stefansaraev** [comment]
thanks. rebased and cherry picked

**Pull request closed without merging**
