### PR TITLE
[build] add BUILD_SUFFIX to the IMAGE_NAME, too.

### PR DESCRIPTION
**Pull request by InuSasha**
actually, different builds (with different changes) on the same commit are overwriting the previous files in target/.
(spezially on non-devel builds)

testet on master and 5.0.6 with release and noobs builds

Sascha

### CODE REVIEW

**Comment by stefansaraev** [comment]
ok from me. doesnt hurt. @sraue ?

**Comment by MilhouseVH** [comment]
Would it be clearer/more flexible if this were called TARGET_SUFFIX, although I appreciate you may always want to set this var as well as BUILD_SUFFIX, however there may also be times when you only want to set one but not the other, or even use different values for TARGET and BUILD suffixes.

**Comment by InuSasha** [comment]
This is a solution, too.
A third way, is to add an OPENELEC_VERSION_SUFFIX.
-> replaces (actual) BUILD_SUFFIX and IMAGE_SUFFIX, additional it is also in version number in the running system.

If you want the OPENELEC_VERSION_SUFFIC or IMAGE_SUFFIX, tell me. I make some tests and PR.

Sascha

**Comment by stefansaraev** [comment]
IMAGE_SUFFIX looks better. but I am fine with whatever makes your life easier ;)

**Comment by InuSasha** [comment]
I switched to IMAGE_SUFFIX. It was tested with master and 5.0.8 in combination with release and noobs target.
The OPENELEC_VERSION_SUFFIX is implemented at an other branch (https://github.com/InuSasha/OpenELEC.tv/tree/features/build_openelec-version), if you are interested.

**Comment by stefansaraev** [comment]
IMAGE_SUFFIX is good. and imo enough. thanks.

**Pull request merged**
