### PR TITLE
[systemd] update to systemd-220

### PR DESCRIPTION
**Pull request by lrusak**
This could use some more testing as this systemd release was over a ~3 month period.

There is an issue with the current tarball as it includes generated files. This is noted in the package.mk.
The location of mount and umount must be hard coded now.

Any other suggestions are welcome.

### CODE REVIEW

**Comment by stefansaraev** [comment]
I am against merging this for OE6.

**Comment by lrusak** [comment]
I am too, I would only consider for master ;)

**Comment by stefansaraev** [comment]
master IS in fact 6.0. for next few months, we should be careful with master.

**Comment by sraue** [comment]
still testing 220 here (i have done now the last days), there is one issue to fix (still not sure if its in kodi or udev), other then this issue it works not bad...

**Comment by sraue** [comment]
... this means this PR like it is cant go to master or 6.0 branch...

**Comment by stefansaraev** [comment]
dont waste time on pkg bumps (especialy this one, if you push - I will revert, no matter how well it works for you)

focus on bugfixing instead. we are beta. thanks

**Comment by lrusak** [comment]
Will 6.0 not be branched soon?

**Comment by stefansaraev** [comment]
branched or not. systemd bump is not going in, even into master, in next six months.

**Comment by lrusak** [comment]
ok :+1: then just leave this here for testing.

**Pull request closed without merging**
