### PR TITLE
New amlogic cec driver

### PR DESCRIPTION
**Pull request by gdachs**
New libcec adapter for amlogic devices.
This need this [kernel](https://github.com/codesnake/linux/pull/5) that is patched with a new cec driver.

### CODE REVIEW

**Comment by lrusak** [comment]
The patches apply fine :+1:

**Comment by mcaptur** [comment]
My tv (a thomsom) has flaky CEC support and i don't need it.. with this  patch dmesg is flooded with the following

[11829.652171@1] cec: try 3 times
[11829.652189@1] [amlogic_cec] amlogic_cec_write(): Message transmit failed, ret=0
[11830.652908@1] [amlogic_cec] amlogic_cec_write(): amlogic_cec_write: enter
[11830.722046@1] cec TX status: rx: 0x0; tx: 0x1
[11830.722087@1] CEC: tx msg len: 1   dat: 10
[11830.722087@1] CEC: tx state: 0
[11830.802054@1] cec TX status: rx: 0x0; tx: 0x1
[11830.802095@1] CEC: tx msg len: 1   dat: 10
[11830.802095@1] CEC: tx state: 0
[11830.802152@1] hdmitx: cec: hw reset :logical addr:0x11
[11830.862133@1] cec TX status: rx: 0x0; tx: 0x1
[11830.862181@1] CEC: tx msg len: 1   dat: 10
[11830.862181@1] CEC: tx state: 0
[11830.862222@1] hdmitx: cec: hw reset :logical addr:0x11
[11830.862234@1] cec: ret = 0
[11830.862245@1] cec: try 3 times
[11830.862265@1] [amlogic_cec] amlogic_cec_write(): Message transmit failed, ret=0
[11830.862622@1] [amlogic_cec] amlogic_cec_write(): amlogic_cec_write: enter
[11830.932276@1] cec TX status: rx: 0x0; tx: 0x1
[11830.932319@1] CEC: tx msg len: 1   dat: 10
[11830.932319@1] CEC: tx state: 0
[11831.012074@1] cec TX status: rx: 0x0; tx: 0x1
[11831.012115@1] CEC: tx msg len: 1   dat: 10
[11831.012115@1] CEC: tx state: 0
[11831.012154@1] hdmitx: cec: hw reset :logical addr:0x11
[11831.072036@1] cec TX status: rx: 0x0; tx: 0x1
[11831.072076@1] CEC: tx msg len: 1   dat: 10
[11831.072076@1] CEC: tx state: 0
[11831.072107@1] hdmitx: cec: hw reset :logical addr:0x11
[11831.072118@1] cec: ret = 0
[11831.072129@1] cec: try 3 times
[11831.072147@1] [amlogic_cec] amlogic_cec_write(): Message transmit failed, ret=0

I tried disabling CEC from within kodi settings, but still get these entries.. is there another way to disable CEC?

**Comment by gdachs** [comment]
I don't know another way to disable cec. If disabling in kodi settings doesn't work, then this would be a libcec issue.

**Comment by mcaptur** [comment]
Actually needed to reboot openelec for setting to take effect.

**Comment by gdachs** [comment]
Has nothing to do with my changes, but good to hear that it works now for you.

**Pull request merged**
