### PR TITLE
Use pkg-config mechanism to synchronize compile flags and paths between VDR and VDR plugins instead of tons of patches.

### PR DESCRIPTION
**Pull request by hsteinhaus**
Doing so allows to use the default Makefiles supplied by VDR plugins without any patching. This is a big gain in maintainability, as a plugin update now usually done by incrementing the version number in the package.mk file - no more manual patch rectification after plugin makefile changes needed. 

Additionally, the pkg-config mechanism ensures absolutely consistent compile flags between VDR and plugins. Inconsistent flags are often a source for unloadable VDR plugins due to symbol resolve issues (and a reason for more OpenELEC plugin patches).

### CODE REVIEW

**Comment by stefansaraev** [comment]
good one. +1 as long "scripts/create_addon vdr-addon" produces working addon

**Comment by MilhouseVH** [comment]
Got a problem building `vdr-satip` (for RPi) with this PR:

```
  UNPACK   vdr-satip
  BUILD    vdr-satip (target)
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-6.0-devel/toolchain/bin/armv6zk-openelec-linux-gnueabi-g++ -march=armv6zk -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"satip"' -DGITVERSION='"-GIT-0.90.0-15968-g60c4d40"'  -o satip.o satip.c
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-6.0-devel/toolchain/bin/armv6zk-openelec-linux-gnueabi-g++ -march=armv6zk -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"satip"' -DGITVERSION='"-GIT-0.90.0-15968-g60c4d40"'  -o common.o common.c
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-6.0-devel/toolchain/bin/armv6zk-openelec-linux-gnueabi-g++ -march=armv6zk -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"satip"' -DGITVERSION='"-GIT-0.90.0-15968-g60c4d40"'  -o config.o config.c
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-6.0-devel/toolchain/bin/armv6zk-openelec-linux-gnueabi-g++ -march=armv6zk -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"satip"' -DGITVERSION='"-GIT-0.90.0-15968-g60c4d40"'  -o device.o device.c
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-6.0-devel/toolchain/bin/armv6zk-openelec-linux-gnueabi-g++ -march=armv6zk -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mcpu=arm1176jzf-s -mfloat-abi=hard -mfpu=vfp -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects  -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"satip"' -DGITVERSION='"-GIT-0.90.0-15968-g60c4d40"'  -o discover.o discover.c
discover.c:12:24: fatal error: pugixml.hpp: No such file or directory
compilation terminated.
Makefile:91: recipe for target 'discover.o' failed
make: *** [discover.o] Error 1
make: *** Waiting for unfinished jobs....
device.c: In member function 'virtual bool cSatipDevice::ProvidesChannel(const cChannel*, int, bool*) const':
device.c:259:36: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
               if (channelP->Vpid() && !HasPid(channelP->Vpid()) || channelP->Apid(0) && !HasPid(channelP->Apid(0)) || channelP->Dpid(0) && !HasPid(channelP->Dpid(0))) {
                                    ^
device.c:259:137: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
               if (channelP->Vpid() && !HasPid(channelP->Vpid()) || channelP->Apid(0) && !HasPid(channelP->Apid(0)) || channelP->Dpid(0) && !HasPid(channelP->Dpid(0))) {
                                                                                                                                         ^
make: *** wait: No child processes.  Stop.
```

**Comment by hsteinhaus** [comment]
Very interesting. According to vdr-satip/README, libpugixml is a mandatory build requirement for vdr-satip - however OpenELEC currently does not satisfy it.

I have libpugixml in my repo, so I guess this is the reason why I probably don't get the error. But here comes the problem: none of the patches of this PR even mentions "pugi" - I guess the problem is not really related to my change, but must have been covered up in some way in the past. 

My suggestion to resolve that: I could send a PR for a libpugixml package in a new PR.

Howeever, I just started a clean master build to debug this issue.

**Comment by stefansaraev** [comment]
> My suggestion to resolve that: I could send a PR for a libpugixml package in a new PR.

nope. it is optional dependency. we use tinyxml instead. no new dependencies for no good reason, please.

**Comment by hsteinhaus** [comment]
Ok, problem understood - fix follows.

**Comment by hsteinhaus** [comment]
Build problem resolved - obviously a define that told vdr-satip to rely on tinyxml instead of pugixml got lost in editing space.

**Comment by MilhouseVH** [comment]
Looks good - I've now built `vdr-addon` successfully for RPi2 and Generic (although I've not installed the add-on, as I have no use for it myself)..

**Comment by hsteinhaus** [comment]
I did a short runtime test on RPi2 in with my private branch of OE6. Unfortunately I cannot test the complete addon with resonable effort, as my target setup does not include kodi/XBMC.

**Comment by sraue** [comment]
@stefansaraev ok?

**Comment by stefansaraev** [comment]
vdr+dvbapi+vnsiserver works for me. other plugins I cant runtime test. but if they compile - all good.

**Pull request merged**
