### PR TITLE
[Python] update to 2.7.10

### PR DESCRIPTION
**Pull request by lrusak**
This PR is a result of the discussion in #4279 

Let me know if I should squash Python-2.7.10-007_enable_cross_compiling.patch into Python-2.7.10-001_xcompile.patch as they are related.

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks. you may squash everything into one commit ;)

**Comment by lrusak** [comment]
Squashed and merged the patches as that made more sense to me as they patch the same file for the same thing.

**Comment by stefansaraev** [comment]
@MilhouseVH do you include this in your builds. if so. any regressions reported ?

**Comment by MilhouseVH** [comment]
Yes, I've been including it since 19 August and no issues reported so far.

**Comment by stefansaraev** [comment]
thanks @MilhouseVH 
@sraue I always protest major bumps, but this fixes a bug. up to you
thanks @lrusak for taking care

**Comment by sraue** [comment]
@stefansaraev what for a bug?

**Comment by lrusak** [comment]
@sraue see,
https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package
https://github.com/OpenELEC/OpenELEC.tv/pull/4279
https://github.com/Alexqw/xbmc-gamepass/issues/183

**Pull request closed without merging**
