### PR TITLE
[WIP] Add docker support to all projects

### PR DESCRIPTION
**Pull request by sony2**
https://github.com/OpenELEC/OpenELEC.tv/pull/4256

Add support for all projects: 
* [x] Generic (OE 6.0)
* [x] Nvidia_Legacy (OE 6.0)
* [ ] RPi
* [ ] RPi2 
* WeTek_Play - old kernel
* imx6 - old kernel

### CODE REVIEW

**Comment by sony2** [comment]
For run docker I need libdevmapper:

PKG_NAME="LVM2"
PKG_VERSION="2.02.127"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="GPL"
PKG_SITE="http://redhat.com"
PKG_URL="ftp://sources.redhat.com/pub/lvm2/LVM2.$PKG_VERSION.tgz"
PKG_SOURCE_DIR="LVM2.$PKG_VERSION"
PKG_PRIORITY="optional"
PKG_SECTION="system"
PKG_SHORTDESC="device mapper."
PKG_LONGDESC="device mapper."

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"


pre_configure_target() {
  export CFLAGS="$CFLAGS -fPIC -DPIC"
}

make_target() {
  make device-mapper
}

makeinstall_target() {
  make install_device-mapper
}

But when I build I receive this error:

/tmp/cc7ttLBw.ltrans1.ltrans.o:<artificial>:function _display_info.lto_priv.52: error: undefined reference to 'dm_task_get_info'
/tmp/cc7ttLBw.ltrans1.ltrans.o:<artificial>:function _display_info.lto_priv.52: error: undefined reference to 'dm_task_get_info'
/tmp/cc7ttLBw.ltrans5.ltrans.o:<artificial>:function _mangle.lto_priv.30: error: undefined reference to 'dm_task_get_info'
/tmp/cc7ttLBw.ltrans5.ltrans.o:<artificial>:function _stats_create.lto_priv.51: error: undefined reference to 'dm_task_get_info'
collect2: error: ld returned 1 exit status

Any suggestion?

**Comment by lrusak** [comment]
I got it to build using this, http://sprunge.us/KINL

However I am not really into having LVM in OpenELEC.

**Comment by sony2** [comment]
Thanks @lrusak, it works. I'm testing with RPi2.

**Comment by sony2** [comment]
@lrusak for intel platform there is no need of this dependency, I´m trying to build the docker version for RPi and it need some patches (i will remove libdevmapper dependency).

**Comment by sony2** [comment]
I have already tested the changes in all the devices I have (Generic, Nvidia_Legacy and RPi2). Now, about the rest of platforms I don't have, do you have any suggestions on how to test them? How do you usually manage to try them all?

**Comment by sraue** [comment]
simply enable/change all kernel config options like on the other projects so the changes are similiar

**Comment by popcornmix** [comment]
@sony2 are you sure all the config options are required?
We added docker support to the default Pi kernel here: https://github.com/raspberrypi/linux/pull/1027
Some options like CONFIG_MEMCG_SWAP will affect performance and I'm reluctant to risk making OpenELEC slower for everyone for a feature that very few will make use of.

Can you check if the options in https://github.com/raspberrypi/linux/pull/1027 give the features you need?

**Comment by sraue** [comment]
do we really need all this kernel config changes? if MEMCG is not needed and bad on RPi, do we need this for our x86 projects?

**Comment by sony2** [comment]
Sorry about the late reply, I was on holiday.

It´s better to have MEMCG active, but the performance in RPi is bad by the moment.

**Comment by vaskas** [comment]
@sony2 I can help with testing on imx6

**Comment by lrusak** [comment]
@sony2 After looking into this I have some findings.

Initially support should only be brought to the Generic, Generic_legacy, RPi, and RPi2 platforms. The imx6 and WeTek_Play use too old of kernels to use overlayfs (which is the easiest to setup because OpenELEC uses ext4 filesystem).

Take a look at my branch where I have docker compiling as an add-on for OE.
https://github.com/OpenELEC/OpenELEC.tv/compare/master...lrusak:docker

If you have any questions please ask. I have tested on Generic and RPi2 with success.

Using the docker provided tool [here](https://github.com/docker/docker/blob/master/contrib/check-config.sh) I adjusted the RPi2 kernel config. I have MEMCG but no MEMCG_SWAP or MEMCG_KMEM. Maybe @popcornmix can take a look at this on my branch as well.

You can drop the changes to systemd-addon-wrapper, they are not needed.

So for now please focus on Generic_Legacy, RPi and RPi2. Please rebase, squash and cleanup your commits.

**Comment by vaskas** [comment]
@lrusak @sony2 can we possibly add a similar patch (just without overlayfs) to support the generic LXC or `systemd-nspawn` (my actual use case) on imx6? That is, until the kernel is updated?

**Comment by lrusak** [comment]
@vaskas yes I can, I have already built lxc and can make it an addon, might be able to package systemd-nspawn as well. Please ping me on IRC or email me so we can take the discussion off github.

**Comment by sony2** [comment]
Sorry, the last few weeks have been very busy.

I have studied imx6 and WeTek_Play and effectively the kernel is too old.
This weekend I will rebase, squash and cleanup my commits.

**Comment by sony2** [comment]
@lrusak Is now the code ok to merge?

**Comment by lrusak** [comment]
Looks fine to me. @sraue it's up to you.

**Comment by mrmachine** [comment]
I'd love to try this on the nvidia_legacy project. Is there any nightly test build I can try before this is merged in?

**Comment by MilhouseVH** [comment]
All of the Nvidia_Legacy kernel options added here appear to be in master and OE 6 already, most likely as defaults with the 4.3 kernel, so try OE6.

This PR needs rebasing, or closing (the RPi/RPi2 kernel options might need rebasing).

**Comment by sony2** [comment]
I need to check the master and then I will rebase the options needed.

**Comment by mrmachine** [comment]
Why is this closed?

**Pull request closed without merging**
