### PR TITLE
vdr-addon bump 6.0.2

### PR DESCRIPTION
**Pull request by CvH**
update to latest rls of sat>ip and vnsi-server

not yet compile/runtime tested

### CODE REVIEW

**Comment by lrusak** [comment]
Let me know if you have compiled/runtime tested

**Comment by lrusak** [comment]
Please test now that #4602 has been merged

**Comment by sraue** [comment]
we also need the same on master, master should be never behind 6.0

**Comment by CvH** [comment]
@sraue 
I pr a bump for master - this is only a "safe bump" and too ancient for master

**Pull request merged**
